// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 and cmd/split-client. DO NOT EDIT.

package flexera

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
	"time"
)

// Defines values for FinopsCustomizationsFilterV1Type.
const (
	FinopsCustomizationsFilterV1TypeAnd       FinopsCustomizationsFilterV1Type = "and"
	FinopsCustomizationsFilterV1TypeEqual     FinopsCustomizationsFilterV1Type = "equal"
	FinopsCustomizationsFilterV1TypeNot       FinopsCustomizationsFilterV1Type = "not"
	FinopsCustomizationsFilterV1TypeOr        FinopsCustomizationsFilterV1Type = "or"
	FinopsCustomizationsFilterV1TypeSubstring FinopsCustomizationsFilterV1Type = "substring"
)

// Defines values for FinopsCustomizationsFlexeraCustomizationsPrincipalKind.
const (
	FinopsCustomizationsFlexeraCustomizationsPrincipalKindIamServiceAccount FinopsCustomizationsFlexeraCustomizationsPrincipalKind = "iam:service-account"
	FinopsCustomizationsFlexeraCustomizationsPrincipalKindIamUser           FinopsCustomizationsFlexeraCustomizationsPrincipalKind = "iam:user"
)

// Defines values for FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionDashboardScope.
const (
	FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionDashboardScopeOrg  FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionDashboardScope = "org"
	FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionDashboardScopeUser FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionDashboardScope = "user"
)

// Defines values for FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionKind.
const (
	FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionKindFinopsReportSubscription FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionKind = "finops:report-subscription"
)

// Defines values for FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionVisibility.
const (
	FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionVisibilityPrivate FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionVisibility = "private"
	FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionVisibilityShared  FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionVisibility = "shared"
)

// Defines values for FinopsCustomizationsFlexeraFinopsCustomizationsRuleBasedDimensionKind.
const (
	FinopsRuleBasedDimension FinopsCustomizationsFlexeraFinopsCustomizationsRuleBasedDimensionKind = "finops:rule-based-dimension"
)

// Defines values for FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryKind.
const (
	FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryKindFinopsSavedFilter FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryKind = "finops:saved-filter"
)

// Defines values for FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryVisibility.
const (
	FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryVisibilityPrivate FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryVisibility = "private"
	FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryVisibilityShared  FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryVisibility = "shared"
)

// Defines values for FinopsCustomizationsFlexeraFinopsCustomizationsTagDimensionKind.
const (
	FinopsTagDimension FinopsCustomizationsFlexeraFinopsCustomizationsTagDimensionKind = "finops:tag-dimension"
)

// Defines values for FinopsCustomizationsIndexSavedFiltersResultKind.
const (
	FinopsSavedFilterList FinopsCustomizationsIndexSavedFiltersResultKind = "finops:saved-filter-list"
)

// Defines values for FinopsCustomizationsPatchSavedFilterRequestVisibility.
const (
	FinopsCustomizationsPatchSavedFilterRequestVisibilityPrivate FinopsCustomizationsPatchSavedFilterRequestVisibility = "private"
	FinopsCustomizationsPatchSavedFilterRequestVisibilityShared  FinopsCustomizationsPatchSavedFilterRequestVisibility = "shared"
)

// Defines values for FinopsCustomizationsReportSubscriptionListKind.
const (
	FinopsReportSubscriptionList FinopsCustomizationsReportSubscriptionListKind = "finops:report-subscription-list"
)

// Defines values for FinopsCustomizationsReportSubscriptionRecipientType.
const (
	FinopsCustomizationsReportSubscriptionRecipientTypeEmail FinopsCustomizationsReportSubscriptionRecipientType = "email"
	FinopsCustomizationsReportSubscriptionRecipientTypeGroup FinopsCustomizationsReportSubscriptionRecipientType = "group"
	FinopsCustomizationsReportSubscriptionRecipientTypeUser  FinopsCustomizationsReportSubscriptionRecipientType = "user"
)

// Defines values for FinopsCustomizationsReportSubscriptionResultDashboardScope.
const (
	FinopsCustomizationsReportSubscriptionResultDashboardScopeOrg  FinopsCustomizationsReportSubscriptionResultDashboardScope = "org"
	FinopsCustomizationsReportSubscriptionResultDashboardScopeUser FinopsCustomizationsReportSubscriptionResultDashboardScope = "user"
)

// Defines values for FinopsCustomizationsReportSubscriptionResultKind.
const (
	FinopsCustomizationsReportSubscriptionResultKindFinopsReportSubscription FinopsCustomizationsReportSubscriptionResultKind = "finops:report-subscription"
)

// Defines values for FinopsCustomizationsReportSubscriptionResultVisibility.
const (
	FinopsCustomizationsReportSubscriptionResultVisibilityPrivate FinopsCustomizationsReportSubscriptionResultVisibility = "private"
	FinopsCustomizationsReportSubscriptionResultVisibilityShared  FinopsCustomizationsReportSubscriptionResultVisibility = "shared"
)

// Defines values for FinopsCustomizationsReportSubscriptionScheduleDayOfWeek.
const (
	Friday    FinopsCustomizationsReportSubscriptionScheduleDayOfWeek = "friday"
	Monday    FinopsCustomizationsReportSubscriptionScheduleDayOfWeek = "monday"
	Saturday  FinopsCustomizationsReportSubscriptionScheduleDayOfWeek = "saturday"
	Sunday    FinopsCustomizationsReportSubscriptionScheduleDayOfWeek = "sunday"
	Thursday  FinopsCustomizationsReportSubscriptionScheduleDayOfWeek = "thursday"
	Tuesday   FinopsCustomizationsReportSubscriptionScheduleDayOfWeek = "tuesday"
	Wednesday FinopsCustomizationsReportSubscriptionScheduleDayOfWeek = "wednesday"
)

// Defines values for FinopsCustomizationsReportSubscriptionScheduleFrequency.
const (
	FinopsCustomizationsReportSubscriptionScheduleFrequencyDaily   FinopsCustomizationsReportSubscriptionScheduleFrequency = "daily"
	FinopsCustomizationsReportSubscriptionScheduleFrequencyMonthly FinopsCustomizationsReportSubscriptionScheduleFrequency = "monthly"
	FinopsCustomizationsReportSubscriptionScheduleFrequencyWeekly  FinopsCustomizationsReportSubscriptionScheduleFrequency = "weekly"
)

// Defines values for FinopsCustomizationsRuleBasedDimensionConditionType.
const (
	And               FinopsCustomizationsRuleBasedDimensionConditionType = "and"
	DimensionContains FinopsCustomizationsRuleBasedDimensionConditionType = "dimension_contains"
	DimensionEquals   FinopsCustomizationsRuleBasedDimensionConditionType = "dimension_equals"
	Not               FinopsCustomizationsRuleBasedDimensionConditionType = "not"
	Or                FinopsCustomizationsRuleBasedDimensionConditionType = "or"
)

// Defines values for FinopsCustomizationsRuleBasedDimensionListKind.
const (
	FinopsRuleBasedDimensionList FinopsCustomizationsRuleBasedDimensionListKind = "finops:rule-based-dimension-list"
)

// Defines values for FinopsCustomizationsRuleBasedDimensionRuleKind.
const (
	FinopsRuleBasedDimensionRule FinopsCustomizationsRuleBasedDimensionRuleKind = "finops:rule-based-dimension-rule"
)

// Defines values for FinopsCustomizationsRuleBasedDimensionRuleListKind.
const (
	FinopsRuleBasedDimensionRuleList FinopsCustomizationsRuleBasedDimensionRuleListKind = "finops:rule-based-dimension-rule-list"
)

// Defines values for FinopsCustomizationsRuleBasedDimensionRuleListLinkKind.
const (
	FinopsRuleBasedDimensionRuleListLink FinopsCustomizationsRuleBasedDimensionRuleListLinkKind = "finops:rule-based-dimension-rule-list-link"
)

// Defines values for FinopsCustomizationsRuleBasedDimensionSummaryKind.
const (
	FinopsRuleBasedDimensionSummary FinopsCustomizationsRuleBasedDimensionSummaryKind = "finops:rule-based-dimension-summary"
)

// Defines values for FinopsCustomizationsSavedFilterHTTPBodyKind.
const (
	FinopsCustomizationsSavedFilterHTTPBodyKindFinopsSavedFilter FinopsCustomizationsSavedFilterHTTPBodyKind = "finops:saved-filter"
)

// Defines values for FinopsCustomizationsSavedFilterHTTPBodyVisibility.
const (
	FinopsCustomizationsSavedFilterHTTPBodyVisibilityPrivate FinopsCustomizationsSavedFilterHTTPBodyVisibility = "private"
	FinopsCustomizationsSavedFilterHTTPBodyVisibilityShared  FinopsCustomizationsSavedFilterHTTPBodyVisibility = "shared"
)

// Defines values for FinopsCustomizationsTagDimensionListKind.
const (
	FinopsTagDimensionList FinopsCustomizationsTagDimensionListKind = "finops:tag-dimension-list"
)

// Defines values for FinopsCustomizationsSavedFiltersIndexParamsVisibility.
const (
	FinopsCustomizationsSavedFiltersIndexParamsVisibilityPrivate FinopsCustomizationsSavedFiltersIndexParamsVisibility = "private"
	FinopsCustomizationsSavedFiltersIndexParamsVisibilityShared  FinopsCustomizationsSavedFiltersIndexParamsVisibility = "shared"
)

// FinopsCustomizationsError invalid skiptoken received
type FinopsCustomizationsError struct {
	// Fault Is the error a server-side fault?
	Fault bool `json:"fault"`

	// Id ID is a unique identifier for this particular occurrence of the problem.
	Id string `json:"id"`

	// Message Message is a human-readable explanation specific to this occurrence of the problem.
	Message string `json:"message"`

	// Name Name is the name of this class of errors.
	Name string `json:"name"`

	// Temporary Is the error temporary?
	Temporary bool `json:"temporary"`

	// Timeout Is the error a timeout?
	Timeout bool `json:"timeout"`
}

// FinopsCustomizationsFilterV1 A single filter node: a leaf test (equal, substring) or a boolean combinator (and, or, not).
type FinopsCustomizationsFilterV1 struct {
	// Dimension Column/dimension name; used by leaf nodes (equal, substring)
	Dimension *string `json:"dimension,omitempty"`

	// Expression A single filter node: a leaf test (equal, substring) or a boolean combinator (and, or, not).
	Expression *FinopsCustomizationsFilterV1 `json:"expression,omitempty"`

	// Expressions Child expressions; used by and/or nodes
	Expressions *[]FinopsCustomizationsFilterV1 `json:"expressions,omitempty"`

	// Substring Substring match value; used by substring nodes
	Substring *string `json:"substring,omitempty"`

	// Type Filter node type
	Type *FinopsCustomizationsFilterV1Type `json:"type,omitempty"`

	// Value Exact match value; used by equal nodes
	Value *string `json:"value,omitempty"`
}

// FinopsCustomizationsFilterV1Type Filter node type
type FinopsCustomizationsFilterV1Type string

// FinopsCustomizationsFlexeraCustomizationsPrincipal A principal is an entity which may perform actions in Flexera One. Users and service accounts are examples of principals.
type FinopsCustomizationsFlexeraCustomizationsPrincipal struct {
	// Id The principal's unique identifier (ID)
	Id int `json:"id"`

	// Kind The resource's type
	Kind FinopsCustomizationsFlexeraCustomizationsPrincipalKind `json:"kind"`

	// Ref A string used to refer to an instance of a resource
	Ref string `json:"ref"`
}

// FinopsCustomizationsFlexeraCustomizationsPrincipalKind The resource's type
type FinopsCustomizationsFlexeraCustomizationsPrincipalKind string

// FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscription A scheduled email report of a dashboard.
type FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscription struct {
	// CreatedAt ISO-8601 creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// DashboardId Identifier of the dashboard to render and send.
	DashboardId string `json:"dashboardId"`

	// DashboardScope Which dashboard store resolves the target dashboard.
	DashboardScope FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionDashboardScope `json:"dashboardScope"`

	// Enabled Whether the schedule is active.
	Enabled bool `json:"enabled"`

	// Id UUID v4 identifier of the report subscription
	Id openapi_types.UUID `json:"id"`

	// Kind The resource's type
	Kind FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionKind `json:"kind"`

	// LastError Error from the last failed attempt; a success does not clear it.
	LastError *string `json:"lastError,omitempty"`

	// LastFailureAt ISO-8601 timestamp of the last failed send attempt.
	LastFailureAt *time.Time `json:"lastFailureAt,omitempty"`

	// LastSuccessAt ISO-8601 timestamp of the last successful send.
	LastSuccessAt *time.Time `json:"lastSuccessAt,omitempty"`

	// Name Human-readable name for the subscription
	Name string `json:"name"`

	// OrgId The unique identifier for the organization
	OrgId int `json:"orgId"`

	// OwnerUserId User ID of the subscription owner
	OwnerUserId int `json:"ownerUserId"`

	// Recipients Delivery targets (at least one).
	Recipients []FinopsCustomizationsReportSubscriptionRecipient `json:"recipients"`

	// Schedule When a scheduled report fires.
	Schedule FinopsCustomizationsReportSubscriptionSchedule `json:"schedule"`

	// UpdatedAt ISO-8601 last-update timestamp
	UpdatedAt time.Time `json:"updatedAt"`

	// Visibility Visibility scope: `private` = only visible to the owner; `shared` = visible to other users in the org.
	Visibility FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionVisibility `json:"visibility"`
}

// FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionDashboardScope Which dashboard store resolves the target dashboard.
type FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionDashboardScope string

// FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionKind The resource's type
type FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionKind string

// FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionVisibility Visibility scope: `private` = only visible to the owner; `shared` = visible to other users in the org.
type FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscriptionVisibility string

// FinopsCustomizationsFlexeraFinopsCustomizationsRuleBasedDimension A rule-based dimension that will be populated by the given rules.
type FinopsCustomizationsFlexeraFinopsCustomizationsRuleBasedDimension struct {
	// CreatedAt timestamp when the rule-based dimension was created
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy A principal is an entity which may perform actions in Flexera One. Users and service accounts are examples of principals.
	CreatedBy *FinopsCustomizationsFlexeraCustomizationsPrincipal `json:"createdBy,omitempty"`

	// Id ID of the rule-based dimension
	Id string `json:"id"`

	// Kind The resource's type
	Kind FinopsCustomizationsFlexeraFinopsCustomizationsRuleBasedDimensionKind `json:"kind"`

	// Name Display name for the dimension in the UI
	Name string `json:"name"`

	// RuleListLinks Links to the rule lists that exist for this dimension, each identified by its effectiveAt date.
	RuleListLinks []FinopsCustomizationsRuleBasedDimensionRuleListLink `json:"ruleListLinks"`

	// UpdatedAt timestamp when the rule-based dimension was updated
	UpdatedAt time.Time `json:"updatedAt"`

	// UpdatedBy A principal is an entity which may perform actions in Flexera One. Users and service accounts are examples of principals.
	UpdatedBy *FinopsCustomizationsFlexeraCustomizationsPrincipal `json:"updatedBy,omitempty"`
}

// FinopsCustomizationsFlexeraFinopsCustomizationsRuleBasedDimensionKind The resource's type
type FinopsCustomizationsFlexeraFinopsCustomizationsRuleBasedDimensionKind string

// FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterError An error describing a favorite saved filter ID that could not be resolved or accessed.
type FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterError struct {
	// Code HTTP status code associated with the unresolved favorite saved filter.
	Code int64 `json:"code"`

	// Id UUID v4 identifier of the favorite saved filter.
	Id openapi_types.UUID `json:"id"`

	// Message Contextual message describing why the favorite saved filter could not be resolved.
	Message string `json:"message"`
}

// FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummary Saved filter summary used in list responses (filter field omitted)
type FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummary struct {
	// CreatedAt ISO-8601 creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description
	Description *string `json:"description,omitempty"`

	// Dimensions Optional list of dimensions for GROUP BY (max 10)
	Dimensions *[]string `json:"dimensions,omitempty"`

	// DowngradedAt Read-only, nullable timestamp of the most recent administrator downgrade from shared to private.
	DowngradedAt *time.Time `json:"downgradedAt,omitempty"`

	// DowngradedByUserId Read-only, nullable user ID of the administrator who most recently downgraded the saved filter from shared to private.
	DowngradedByUserId *int `json:"downgradedByUserId,omitempty"`

	// FilterExpressionCount Number of filter expressions (leaf predicates) used by the filter
	FilterExpressionCount int `json:"filterExpressionCount"`

	// GroupByExpressionCount Number of GROUP BY expressions (dimensions)
	GroupByExpressionCount int `json:"groupByExpressionCount"`

	// Id UUID v4 identifier
	Id openapi_types.UUID `json:"id"`

	// IsFavorite Indicates if the filter is marked as favorite
	IsFavorite *bool `json:"isFavorite,omitempty"`

	// Kind The resource's type
	Kind FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryKind `json:"kind"`

	// Name Human-readable name
	Name string `json:"name"`

	// OrgId The unique identifier for the organization
	OrgId int `json:"orgId"`

	// OwnerUserId User ID of the filter owner
	OwnerUserId int `json:"ownerUserId"`

	// UpdatedAt ISO-8601 last-update timestamp
	UpdatedAt time.Time `json:"updatedAt"`

	// Visibility Filter visibility
	Visibility FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryVisibility `json:"visibility"`
}

// FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryKind The resource's type
type FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryKind string

// FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryVisibility Filter visibility
type FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummaryVisibility string

// FinopsCustomizationsFlexeraFinopsCustomizationsTagDimension Configuration for a tag dimension
type FinopsCustomizationsFlexeraFinopsCustomizationsTagDimension struct {
	// CreatedAt the time when this tag dimension configuration was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Identifier of the tag dimension.
	Id string `json:"id"`

	// Kind The resource's type
	Kind FinopsCustomizationsFlexeraFinopsCustomizationsTagDimensionKind `json:"kind"`

	// Name Name of the tag dimension to be displayed in the UI.
	Name string `json:"name"`

	// Tags Specifies the resource tag keys used to derive values for this dimension. If a resource has multiple matching tags, the value from the earliest listed tag is used.
	Tags []FinopsCustomizationsTagDimensionTag `json:"tags"`

	// UpdatedAt the time when this tag dimension configuration was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// FinopsCustomizationsFlexeraFinopsCustomizationsTagDimensionKind The resource's type
type FinopsCustomizationsFlexeraFinopsCustomizationsTagDimensionKind string

// FinopsCustomizationsIndexSavedFiltersResult defines model for FinopsCustomizations_IndexSavedFiltersResult.
type FinopsCustomizationsIndexSavedFiltersResult struct {
	// Count Number of items in the current page.
	Count  *int                                            `json:"count,omitempty"`
	Errors *FinopsCustomizationsSavedFilterErrorCollection `json:"errors,omitempty"`

	// Kind The resource's type
	Kind FinopsCustomizationsIndexSavedFiltersResultKind `json:"kind"`

	// NextPage URL to the next page of data. If nextPage is not present, the returned page of data is the last.
	NextPage *string `json:"nextPage,omitempty"`

	// PrevPage URL to the previous page of data. The first page of data will not return a prevPage value.
	PrevPage *string `json:"prevPage,omitempty"`

	// Total Total number of items matching the current filter.
	Total  *int                                             `json:"total,omitempty"`
	Values FinopsCustomizationsSavedFilterSummaryCollection `json:"values"`
}

// FinopsCustomizationsIndexSavedFiltersResultKind The resource's type
type FinopsCustomizationsIndexSavedFiltersResultKind string

// FinopsCustomizationsPatchSavedFilterRequest defines model for FinopsCustomizations_PatchSavedFilterRequest.
type FinopsCustomizationsPatchSavedFilterRequest struct {
	// Description Updated description. Use null to clear the description.
	Description *string `json:"description,omitempty"`

	// Dimensions Updated list of dimensions for GROUP BY. Use null to clear dimensions.
	Dimensions *[]string `json:"dimensions,omitempty"`

	// Filter A single filter node: a leaf test (equal, substring) or a boolean combinator (and, or, not).
	Filter *FinopsCustomizationsFilterV1 `json:"filter,omitempty"`

	// Name Updated name.
	Name *string `json:"name,omitempty"`

	// Visibility Updated filter visibility scope.
	Visibility *FinopsCustomizationsPatchSavedFilterRequestVisibility `json:"visibility,omitempty"`
}

// FinopsCustomizationsPatchSavedFilterRequestVisibility Updated filter visibility scope.
type FinopsCustomizationsPatchSavedFilterRequestVisibility string

// FinopsCustomizationsReportSubscriptionCollection defines model for FinopsCustomizations_ReportSubscriptionCollection.
type FinopsCustomizationsReportSubscriptionCollection = []FinopsCustomizationsFlexeraFinopsCustomizationsReportSubscription

// FinopsCustomizationsReportSubscriptionList defines model for FinopsCustomizations_ReportSubscriptionList.
type FinopsCustomizationsReportSubscriptionList struct {
	// Count Number of items in the current page.
	Count *int `json:"count,omitempty"`

	// Kind The resource's type
	Kind FinopsCustomizationsReportSubscriptionListKind `json:"kind"`

	// NextPage URL to the next page of data. If nextPage is not present, the returned page of data is the last.
	NextPage *string `json:"nextPage,omitempty"`

	// PrevPage URL to the previous page of data. The first page of data will not return a prevPage value.
	PrevPage *string `json:"prevPage,omitempty"`

	// Total Total number of items matching the current filter.
	Total  *int                                             `json:"total,omitempty"`
	Values FinopsCustomizationsReportSubscriptionCollection `json:"values"`
}

// FinopsCustomizationsReportSubscriptionListKind The resource's type
type FinopsCustomizationsReportSubscriptionListKind string

// FinopsCustomizationsReportSubscriptionRecipient A delivery target for a scheduled report.
type FinopsCustomizationsReportSubscriptionRecipient struct {
	// Email Email address (for type email, or the resolved address of a user).
	Email *string `json:"email,omitempty"`

	// Id FlexeraOne user/group id (for type user/group).
	Id *string `json:"id,omitempty"`

	// Type Addressing style.
	Type FinopsCustomizationsReportSubscriptionRecipientType `json:"type"`
}

// FinopsCustomizationsReportSubscriptionRecipientType Addressing style.
type FinopsCustomizationsReportSubscriptionRecipientType string

// FinopsCustomizationsReportSubscriptionResult defines model for FinopsCustomizations_ReportSubscriptionResult.
type FinopsCustomizationsReportSubscriptionResult struct {
	// CreatedAt ISO-8601 creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// DashboardId Identifier of the dashboard to render and send.
	DashboardId string `json:"dashboardId"`

	// DashboardScope Which dashboard store resolves the target dashboard.
	DashboardScope FinopsCustomizationsReportSubscriptionResultDashboardScope `json:"dashboardScope"`

	// Enabled Whether the schedule is active.
	Enabled bool `json:"enabled"`

	// Id UUID v4 identifier of the report subscription
	Id openapi_types.UUID `json:"id"`

	// Kind The resource's type
	Kind FinopsCustomizationsReportSubscriptionResultKind `json:"kind"`

	// LastError Error from the last failed attempt; a success does not clear it.
	LastError *string `json:"lastError,omitempty"`

	// LastFailureAt ISO-8601 timestamp of the last failed send attempt.
	LastFailureAt *time.Time `json:"lastFailureAt,omitempty"`

	// LastSuccessAt ISO-8601 timestamp of the last successful send.
	LastSuccessAt *time.Time `json:"lastSuccessAt,omitempty"`

	// Name Human-readable name for the subscription
	Name string `json:"name"`

	// OrgId The unique identifier for the organization
	OrgId int `json:"orgId"`

	// OwnerUserId User ID of the subscription owner
	OwnerUserId int `json:"ownerUserId"`

	// Recipients Delivery targets (at least one).
	Recipients []FinopsCustomizationsReportSubscriptionRecipient `json:"recipients"`

	// Schedule When a scheduled report fires.
	Schedule FinopsCustomizationsReportSubscriptionSchedule `json:"schedule"`

	// UpdatedAt ISO-8601 last-update timestamp
	UpdatedAt time.Time `json:"updatedAt"`

	// Visibility Visibility scope: `private` = only visible to the owner; `shared` = visible to other users in the org.
	Visibility FinopsCustomizationsReportSubscriptionResultVisibility `json:"visibility"`
}

// FinopsCustomizationsReportSubscriptionResultDashboardScope Which dashboard store resolves the target dashboard.
type FinopsCustomizationsReportSubscriptionResultDashboardScope string

// FinopsCustomizationsReportSubscriptionResultKind The resource's type
type FinopsCustomizationsReportSubscriptionResultKind string

// FinopsCustomizationsReportSubscriptionResultVisibility Visibility scope: `private` = only visible to the owner; `shared` = visible to other users in the org.
type FinopsCustomizationsReportSubscriptionResultVisibility string

// FinopsCustomizationsReportSubscriptionSchedule When a scheduled report fires.
type FinopsCustomizationsReportSubscriptionSchedule struct {
	// DayOfMonth Day of month 1-31 (required for monthly); days beyond a month's length clamp to its last day.
	DayOfMonth *int `json:"dayOfMonth,omitempty"`

	// DayOfWeek Day of week (required for weekly).
	DayOfWeek *FinopsCustomizationsReportSubscriptionScheduleDayOfWeek `json:"dayOfWeek,omitempty"`

	// Frequency How often the report fires.
	Frequency FinopsCustomizationsReportSubscriptionScheduleFrequency `json:"frequency"`

	// TimeOfDay 24-hour local wall-clock time, zero-padded "HH:mm".
	TimeOfDay string `json:"timeOfDay"`

	// Timezone IANA tz database id; timeOfDay is interpreted in this zone.
	Timezone string `json:"timezone"`
}

// FinopsCustomizationsReportSubscriptionScheduleDayOfWeek Day of week (required for weekly).
type FinopsCustomizationsReportSubscriptionScheduleDayOfWeek string

// FinopsCustomizationsReportSubscriptionScheduleFrequency How often the report fires.
type FinopsCustomizationsReportSubscriptionScheduleFrequency string

// FinopsCustomizationsRuleBasedDimensionCollection defines model for FinopsCustomizations_RuleBasedDimensionCollection.
type FinopsCustomizationsRuleBasedDimensionCollection = []FinopsCustomizationsFlexeraFinopsCustomizationsRuleBasedDimension

// FinopsCustomizationsRuleBasedDimensionCondition A condition may be null, which will match unconditionally.
//
// Otherwise, the 'type' field is required and, depending on which type is selected, other field(s) will be required.
// A simple condition is checking whether a dimension in the cost row equals a certain value or contains a certain substring:
// ~~~~
// {"type":"dimension_equals", "dimension":"vendor", "value":"AWS"}
// ~~~~
// ~~~~
// {"type":"dimension_contains", "dimension":"resource_type", "substring":"Compute"}
// ~~~~
// Others types like 'and', 'or', and 'not', are used to build complex expressions.
//
// For example:
// ~~~~
// {"type":"and", "expressions":[
//
//	{"type":"dimension_equals", "dimension":"vendor",  "value":"AWS"},
//	{"type":"dimension_equals", "dimension":"service", "value":"EC2"},
//	{"type":"dimension_contains", "dimension":"resource_type", "substring":"Compute"}
//
// ]}
// ~~~~
// ~~~~
// {"type":"or", "expressions":[
//
//	{"type":"dimension_equals", "dimension":"vendor",  "value":"AWS"},
//	{"type":"dimension_equals", "dimension":"vendor",  "value":"Azure"},
//
// ]}
// ~~~~
// ~~~~
//
//	{"type":"not", "expression": {
//	  "type":"dimension_equals", "dimension":"vendor", "value":"Azure"
//	}}
//
// ~~~~
// ~~~~
//
//	{"type":"not", "expression": {
//	  "type":"dimension_contains", "dimension":"vendor", "substring":"Azure"
//	}}
//
// ~~~~
// The docs are not being generated correctly for the 'expression' field. It is used with the 'not' condition type and contains another expression to be negated.
type FinopsCustomizationsRuleBasedDimensionCondition struct {
	// CaseInsensitive Specifies whether the condition should perform a case-insensitive match.
	CaseInsensitive *bool `json:"caseInsensitive,omitempty"`

	// Dimension The dimension to check the value of. Required for the 'dimension_equals' or 'dimension_contains' type.
	Dimension *string `json:"dimension,omitempty"`

	// Expression A condition may be null, which will match unconditionally.
	//
	// Otherwise, the 'type' field is required and, depending on which type is selected, other field(s) will be required.
	// A simple condition is checking whether a dimension in the cost row equals a certain value or contains a certain substring:
	// ~~~~
	// {"type":"dimension_equals", "dimension":"vendor", "value":"AWS"}
	// ~~~~
	// ~~~~
	// {"type":"dimension_contains", "dimension":"resource_type", "substring":"Compute"}
	// ~~~~
	// Others types like 'and', 'or', and 'not', are used to build complex expressions.
	//
	// For example:
	// ~~~~
	// {"type":"and", "expressions":[
	//   {"type":"dimension_equals", "dimension":"vendor",  "value":"AWS"},
	//   {"type":"dimension_equals", "dimension":"service", "value":"EC2"},
	//   {"type":"dimension_contains", "dimension":"resource_type", "substring":"Compute"}
	// ]}
	// ~~~~
	// ~~~~
	// {"type":"or", "expressions":[
	//   {"type":"dimension_equals", "dimension":"vendor",  "value":"AWS"},
	//   {"type":"dimension_equals", "dimension":"vendor",  "value":"Azure"},
	// ]}
	// ~~~~
	// ~~~~
	// {"type":"not", "expression": {
	//   "type":"dimension_equals", "dimension":"vendor", "value":"Azure"
	// }}
	// ~~~~
	// ~~~~
	// {"type":"not", "expression": {
	//   "type":"dimension_contains", "dimension":"vendor", "substring":"Azure"
	// }}
	// ~~~~
	// The docs are not being generated correctly for the 'expression' field. It is used with the 'not' condition type and contains another expression to be negated.
	Expression *FinopsCustomizationsRuleBasedDimensionCondition `json:"expression,omitempty"`

	// Expressions the expressions that will be AND'd or OR'd together. Required for the 'and' and 'or' types.
	Expressions *[]FinopsCustomizationsRuleBasedDimensionCondition `json:"expressions,omitempty"`

	// Substring The substring that the dimension must contain. Required for the 'dimension_contains' type.
	Substring *string `json:"substring,omitempty"`

	// Type Specifies the condition type, depending on which type is selected, other field(s) will be required.
	Type FinopsCustomizationsRuleBasedDimensionConditionType `json:"type"`

	// Value The value that the dimension must match. Required for the 'dimension_equals' type.
	Value *string `json:"value,omitempty"`
}

// FinopsCustomizationsRuleBasedDimensionConditionType Specifies the condition type, depending on which type is selected, other field(s) will be required.
type FinopsCustomizationsRuleBasedDimensionConditionType string

// FinopsCustomizationsRuleBasedDimensionList defines model for FinopsCustomizations_RuleBasedDimensionList.
type FinopsCustomizationsRuleBasedDimensionList struct {
	// Kind The resource's type
	Kind   FinopsCustomizationsRuleBasedDimensionListKind   `json:"kind"`
	Values FinopsCustomizationsRuleBasedDimensionCollection `json:"values"`
}

// FinopsCustomizationsRuleBasedDimensionListKind The resource's type
type FinopsCustomizationsRuleBasedDimensionListKind string

// FinopsCustomizationsRuleBasedDimensionRule For a given cost row, if the given condition is true, the given value will be used to populate this rule-based dimension.
type FinopsCustomizationsRuleBasedDimensionRule struct {
	// Condition A condition may be null, which will match unconditionally.
	//
	// Otherwise, the 'type' field is required and, depending on which type is selected, other field(s) will be required.
	// A simple condition is checking whether a dimension in the cost row equals a certain value or contains a certain substring:
	// ~~~~
	// {"type":"dimension_equals", "dimension":"vendor", "value":"AWS"}
	// ~~~~
	// ~~~~
	// {"type":"dimension_contains", "dimension":"resource_type", "substring":"Compute"}
	// ~~~~
	// Others types like 'and', 'or', and 'not', are used to build complex expressions.
	//
	// For example:
	// ~~~~
	// {"type":"and", "expressions":[
	//   {"type":"dimension_equals", "dimension":"vendor",  "value":"AWS"},
	//   {"type":"dimension_equals", "dimension":"service", "value":"EC2"},
	//   {"type":"dimension_contains", "dimension":"resource_type", "substring":"Compute"}
	// ]}
	// ~~~~
	// ~~~~
	// {"type":"or", "expressions":[
	//   {"type":"dimension_equals", "dimension":"vendor",  "value":"AWS"},
	//   {"type":"dimension_equals", "dimension":"vendor",  "value":"Azure"},
	// ]}
	// ~~~~
	// ~~~~
	// {"type":"not", "expression": {
	//   "type":"dimension_equals", "dimension":"vendor", "value":"Azure"
	// }}
	// ~~~~
	// ~~~~
	// {"type":"not", "expression": {
	//   "type":"dimension_contains", "dimension":"vendor", "substring":"Azure"
	// }}
	// ~~~~
	// The docs are not being generated correctly for the 'expression' field. It is used with the 'not' condition type and contains another expression to be negated.
	Condition *FinopsCustomizationsRuleBasedDimensionCondition `json:"condition,omitempty"`

	// Kind The resource's type
	Kind FinopsCustomizationsRuleBasedDimensionRuleKind `json:"kind"`

	// Value the value to populate dimension with if condition is met
	Value FinopsCustomizationsRuleBasedDimensionValueExpression `json:"value"`
}

// FinopsCustomizationsRuleBasedDimensionRuleKind The resource's type
type FinopsCustomizationsRuleBasedDimensionRuleKind string

// FinopsCustomizationsRuleBasedDimensionRuleList defines model for FinopsCustomizations_RuleBasedDimensionRuleList.
type FinopsCustomizationsRuleBasedDimensionRuleList struct {
	// CreatedAt timestamp from when the dated-rules were created
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy A principal is an entity which may perform actions in Flexera One. Users and service accounts are examples of principals.
	CreatedBy *FinopsCustomizationsFlexeraCustomizationsPrincipal `json:"createdBy,omitempty"`

	// EffectiveAt The date (year-month) when this rules list takes effect, superseding any previous list. The list remains in effect until a subsequent list is defined to take effect at a later date.
	EffectiveAt string `json:"effectiveAt"`

	// Kind The resource's type
	Kind FinopsCustomizationsRuleBasedDimensionRuleListKind `json:"kind"`

	// Rules Rules for how the dimension will be populated. A rules list normally supports up to 500 rules. A simple mapping-style list may support up to 40,000 raw rules if it optimizes into no more than 500 rule groups. After mapping optimization, plain rules in one list may contain up to 1,000 condition expression elements. Across all rule-based dimensions, a single effective month may have up to 400,000 applicable raw rules in total, and up to 2,000 optimized rule groups after mapping optimization.
	Rules []FinopsCustomizationsRuleBasedDimensionRule `json:"rules"`

	// UpdatedAt timestamp from when the dated-rules were updated
	UpdatedAt time.Time `json:"updatedAt"`

	// UpdatedBy A principal is an entity which may perform actions in Flexera One. Users and service accounts are examples of principals.
	UpdatedBy *FinopsCustomizationsFlexeraCustomizationsPrincipal `json:"updatedBy,omitempty"`
}

// FinopsCustomizationsRuleBasedDimensionRuleListKind The resource's type
type FinopsCustomizationsRuleBasedDimensionRuleListKind string

// FinopsCustomizationsRuleBasedDimensionRuleListLink Link to a rules list, identified by its effectiveAt date.
type FinopsCustomizationsRuleBasedDimensionRuleListLink struct {
	// EffectiveAt The date (year-month) when this rules list takes effect, superseding any previous list. The list remains in effect until a subsequent list is defined to take effect at a later date.
	EffectiveAt string `json:"effectiveAt"`

	// Kind The resource's type
	Kind FinopsCustomizationsRuleBasedDimensionRuleListLinkKind `json:"kind"`

	// RulesCount The count of rules list, identified by its effectiveAt date.
	RulesCount int `json:"rulesCount"`
}

// FinopsCustomizationsRuleBasedDimensionRuleListLinkKind The resource's type
type FinopsCustomizationsRuleBasedDimensionRuleListLinkKind string

// FinopsCustomizationsRuleBasedDimensionRulePayload For a given cost row, if the given condition is true, the given value will be used to populate this rule-based dimension.
type FinopsCustomizationsRuleBasedDimensionRulePayload struct {
	// Condition A condition may be null, which will match unconditionally.
	//
	// Otherwise, the 'type' field is required and, depending on which type is selected, other field(s) will be required.
	// A simple condition is checking whether a dimension in the cost row equals a certain value or contains a certain substring:
	// ~~~~
	// {"type":"dimension_equals", "dimension":"vendor", "value":"AWS"}
	// ~~~~
	// ~~~~
	// {"type":"dimension_contains", "dimension":"resource_type", "substring":"Compute"}
	// ~~~~
	// Others types like 'and', 'or', and 'not', are used to build complex expressions.
	//
	// For example:
	// ~~~~
	// {"type":"and", "expressions":[
	//   {"type":"dimension_equals", "dimension":"vendor",  "value":"AWS"},
	//   {"type":"dimension_equals", "dimension":"service", "value":"EC2"},
	//   {"type":"dimension_contains", "dimension":"resource_type", "substring":"Compute"}
	// ]}
	// ~~~~
	// ~~~~
	// {"type":"or", "expressions":[
	//   {"type":"dimension_equals", "dimension":"vendor",  "value":"AWS"},
	//   {"type":"dimension_equals", "dimension":"vendor",  "value":"Azure"},
	// ]}
	// ~~~~
	// ~~~~
	// {"type":"not", "expression": {
	//   "type":"dimension_equals", "dimension":"vendor", "value":"Azure"
	// }}
	// ~~~~
	// ~~~~
	// {"type":"not", "expression": {
	//   "type":"dimension_contains", "dimension":"vendor", "substring":"Azure"
	// }}
	// ~~~~
	// The docs are not being generated correctly for the 'expression' field. It is used with the 'not' condition type and contains another expression to be negated.
	Condition *FinopsCustomizationsRuleBasedDimensionCondition `json:"condition,omitempty"`

	// Value the value to populate dimension with if condition is met
	Value FinopsCustomizationsRuleBasedDimensionValueExpression `json:"value"`
}

// FinopsCustomizationsRuleBasedDimensionSummary defines model for FinopsCustomizations_RuleBasedDimensionSummary.
type FinopsCustomizationsRuleBasedDimensionSummary struct {
	// Kind The resource's type
	Kind FinopsCustomizationsRuleBasedDimensionSummaryKind `json:"kind"`

	// RuleListLinks Links to available rule lists identified by effectiveAt.
	RuleListLinks []FinopsCustomizationsRuleBasedDimensionRuleListLink `json:"ruleListLinks"`

	// Values All distinct values used across the rules, each with either a static text value or a dimension ID.
	Values []FinopsCustomizationsRuleBasedDimensionValueExpression `json:"values"`
}

// FinopsCustomizationsRuleBasedDimensionSummaryKind The resource's type
type FinopsCustomizationsRuleBasedDimensionSummaryKind string

// FinopsCustomizationsRuleBasedDimensionValueExpression the value to populate dimension with if condition is met
type FinopsCustomizationsRuleBasedDimensionValueExpression struct {
	// Dimension the dynamic dimension value to populate the rule-based dimension if the condition is met
	Dimension *string `json:"dimension,omitempty"`

	// Text the static string value to populate the rule-based dimension if the condition is met
	Text *string `json:"text,omitempty"`
}

// FinopsCustomizationsSavedFilterErrorCollection defines model for FinopsCustomizations_SavedFilterErrorCollection.
type FinopsCustomizationsSavedFilterErrorCollection = []FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterError

// FinopsCustomizationsSavedFilterHTTPBody defines model for FinopsCustomizations_SavedFilterHTTPBody.
type FinopsCustomizationsSavedFilterHTTPBody struct {
	// CreatedAt ISO-8601 creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description
	Description *string `json:"description,omitempty"`

	// Dimensions Optional list of dimensions for GROUP BY (max 10)
	Dimensions *[]string `json:"dimensions,omitempty"`

	// DowngradedAt Read-only, nullable timestamp of the most recent administrator downgrade from shared to private.
	DowngradedAt *time.Time `json:"downgradedAt,omitempty"`

	// DowngradedByUserId Read-only, nullable user ID of the administrator who most recently downgraded the saved filter from shared to private.
	DowngradedByUserId *int `json:"downgradedByUserId,omitempty"`

	// Filter FOCUS 1.0 filter configuration
	Filter map[string]interface{} `json:"filter"`

	// Id UUID v4 identifier of the saved filter
	Id openapi_types.UUID `json:"id"`

	// Kind The resource's type
	Kind FinopsCustomizationsSavedFilterHTTPBodyKind `json:"kind"`

	// Name Human-readable name for the filter
	Name string `json:"name"`

	// OrgId The unique identifier for the organization
	OrgId int `json:"orgId"`

	// OwnerUserId User ID of the filter owner
	OwnerUserId int `json:"ownerUserId"`

	// UpdatedAt ISO-8601 last-update timestamp
	UpdatedAt time.Time `json:"updatedAt"`

	// Visibility Visibility scope: `private` = only visible to the owner; `shared` = visible to other users in the org.
	Visibility FinopsCustomizationsSavedFilterHTTPBodyVisibility `json:"visibility"`
}

// FinopsCustomizationsSavedFilterHTTPBodyKind The resource's type
type FinopsCustomizationsSavedFilterHTTPBodyKind string

// FinopsCustomizationsSavedFilterHTTPBodyVisibility Visibility scope: `private` = only visible to the owner; `shared` = visible to other users in the org.
type FinopsCustomizationsSavedFilterHTTPBodyVisibility string

// FinopsCustomizationsSavedFilterSummaryCollection defines model for FinopsCustomizations_SavedFilterSummaryCollection.
type FinopsCustomizationsSavedFilterSummaryCollection = []FinopsCustomizationsFlexeraFinopsCustomizationsSavedFilterSummary

// FinopsCustomizationsTagDimensionCollection defines model for FinopsCustomizations_TagDimensionCollection.
type FinopsCustomizationsTagDimensionCollection = []FinopsCustomizationsFlexeraFinopsCustomizationsTagDimension

// FinopsCustomizationsTagDimensionList defines model for FinopsCustomizations_TagDimensionList.
type FinopsCustomizationsTagDimensionList struct {
	// Kind The resource's type
	Kind   FinopsCustomizationsTagDimensionListKind   `json:"kind"`
	Values FinopsCustomizationsTagDimensionCollection `json:"values"`
}

// FinopsCustomizationsTagDimensionListKind The resource's type
type FinopsCustomizationsTagDimensionListKind string

// FinopsCustomizationsTagDimensionTag Contains the resource tag key
type FinopsCustomizationsTagDimensionTag struct {
	// Key Key (the part of the tag before the "=" character).
	Key string `json:"key"`
}

// FinopsCustomizationsSavedFiltersIndexParamsVisibility defines parameters for FinopsCustomizationsSavedFiltersIndex.
type FinopsCustomizationsSavedFiltersIndexParamsVisibility string
