// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 and cmd/split-client. DO NOT EDIT.

package flexera

import (
	"context"
	"fmt"
	"github.com/oapi-codegen/runtime"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Defines values for AuthTokenRequestBodyGrantType.
const (
	AuthTokenRequestBodyGrantTypeAuthorizationCode AuthTokenRequestBodyGrantType = "authorization_code"
	AuthTokenRequestBodyGrantTypeClientCredentials AuthTokenRequestBodyGrantType = "client_credentials"
	AuthTokenRequestBodyGrantTypeRefreshToken      AuthTokenRequestBodyGrantType = "refresh_token"
)

// AuthTokenRequestBody defines model for Auth_TokenRequestBody.
type AuthTokenRequestBody struct {
	// ClientId Required if the grant type is "client_credentials".
	// This specifies the "client_id" that was returned when service app was created.
	ClientId *string `json:"client_id,omitempty"`

	// ClientSecret Required if the grant type is "client_credentials".
	// This specifies the "client_secret" that was returned when service app was created.
	ClientSecret *string `json:"client_secret,omitempty"`

	// Code Required if the grant_type is "authorization_code".
	// The value should be what was returned from "https://developer.okta.com/docs/reference/api/oidc/#authorize" endpoint.
	// The code has a lifetime of one minute.
	Code *string `json:"code,omitempty"`

	// GrantType One of the accepted OAuth v2 grant types.
	GrantType AuthTokenRequestBodyGrantType `json:"grant_type"`

	// RedirectUri Required if the grant_type is "authorization_code".
	// The value should be what was returned from "https://developer.okta.com/docs/reference/api/oidc/#authorize" endpoint.
	// The code has a lifetime of one minute.
	RedirectUri *string `json:"redirect_uri,omitempty"`

	// RefreshToken Token returned from a previous call using an authorization code scoped to
	// "offline_access", which is the only argument for grant_type="refresh_token".
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// AuthTokenRequestBodyGrantType One of the accepted OAuth v2 grant types.
type AuthTokenRequestBodyGrantType string

// AuthTokenTokenFormdataRequestBody defines body for AuthTokenToken for application/x-www-form-urlencoded ContentType.
type AuthTokenTokenFormdataRequestBody = AuthTokenRequestBody

func (c *Client) AuthTokenTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthTokenTokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AuthTokenTokenWithFormdataBody(ctx context.Context, body AuthTokenTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthTokenTokenRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAuthTokenTokenRequestWithFormdataBody calls the generic AuthTokenToken builder with application/x-www-form-urlencoded body
func NewAuthTokenTokenRequestWithFormdataBody(server string, body AuthTokenTokenFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewAuthTokenTokenRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewAuthTokenTokenRequestWithBody generates requests for AuthTokenToken with any type of body
func NewAuthTokenTokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/oidc/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}
