// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 and cmd/split-client. DO NOT EDIT.

package flexera

import (
	"context"
	"fmt"
	"github.com/oapi-codegen/runtime"
	"net/http"
	"net/url"
)

// GrsUserOrgIndexParams defines parameters for GrsUserOrgIndex.
type GrsUserOrgIndexParams struct {
	// XApiVersion API version. Defaults to 2.0.
	XApiVersion *string `json:"X-Api-Version,omitempty"`
}

// GrsProjectIndexForOrgParams defines parameters for GrsProjectIndexForOrg.
type GrsProjectIndexForOrgParams struct {
	// XApiVersion API version. Defaults to 2.0.
	XApiVersion *string `json:"X-Api-Version,omitempty"`
}

func (c *Client) GrsUserOrgIndex(ctx context.Context, userId int64, params *GrsUserOrgIndexParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGrsUserOrgIndexRequest(c.Server, userId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GrsProjectIndexForOrg(ctx context.Context, userId int64, params *GrsProjectIndexForOrgParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGrsProjectIndexForOrgRequest(c.Server, userId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGrsUserOrgIndexRequest generates requests for GrsUserOrgIndex
func NewGrsUserOrgIndexRequest(server string, userId int64, params *GrsUserOrgIndexParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "userId", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/grs/users/%s/orgs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XApiVersion != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Api-Version", runtime.ParamLocationHeader, *params.XApiVersion)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Api-Version", headerParam0)
		}

	}

	return req, nil
}

// NewGrsProjectIndexForOrgRequest generates requests for GrsProjectIndexForOrg
func NewGrsProjectIndexForOrgRequest(server string, userId int64, params *GrsProjectIndexForOrgParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "userId", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/grs/users/%s/projects", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XApiVersion != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Api-Version", runtime.ParamLocationHeader, *params.XApiVersion)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Api-Version", headerParam0)
		}

	}

	return req, nil
}
