// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 and cmd/split-client. DO NOT EDIT.

package flexera

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strings"
)

// VisCreateResponseBody defines model for Vis_CreateResponseBody.
type VisCreateResponseBody struct {
	// Id The unique query identifier
	Id string `json:"id"`

	// ResumeToken The next delta value
	ResumeToken *string `json:"resumeToken,omitempty"`
}

type VisDeviceEstimateDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]VisFlexeraVisDeviceDeletionSummary
}

// Status returns HTTPResponse.Status
func (r VisDeviceEstimateDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VisDeviceEstimateDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VisDeviceDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *[]VisFlexeraVisDeviceDeletionSummary
}

// Status returns HTTPResponse.Status
func (r VisDeviceDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VisDeviceDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VisExportIndexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VisExportFileList
}

// Status returns HTTPResponse.Status
func (r VisExportIndexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VisExportIndexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VisExportDownloadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r VisExportDownloadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VisExportDownloadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VisQueryCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VisCreateResponseBody
}

// Status returns HTTPResponse.Status
func (r VisQueryCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VisQueryCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VisQueryShowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VisQueryData
}

// Status returns HTTPResponse.Status
func (r VisQueryShowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VisQueryShowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VisQueryDownloadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r VisQueryDownloadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VisQueryDownloadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// VisDeviceEstimateDeleteWithBodyWithResponse request with arbitrary body returning *VisDeviceEstimateDeleteResponse
func (c *ClientWithResponses) VisDeviceEstimateDeleteWithBodyWithResponse(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VisDeviceEstimateDeleteResponse, error) {
	rsp, err := c.VisDeviceEstimateDeleteWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVisDeviceEstimateDeleteResponse(rsp)
}

func (c *ClientWithResponses) VisDeviceEstimateDeleteWithResponse(ctx context.Context, orgId int, body VisDeviceEstimateDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*VisDeviceEstimateDeleteResponse, error) {
	rsp, err := c.VisDeviceEstimateDelete(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVisDeviceEstimateDeleteResponse(rsp)
}

// VisDeviceDeleteWithBodyWithResponse request with arbitrary body returning *VisDeviceDeleteResponse
func (c *ClientWithResponses) VisDeviceDeleteWithBodyWithResponse(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VisDeviceDeleteResponse, error) {
	rsp, err := c.VisDeviceDeleteWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVisDeviceDeleteResponse(rsp)
}

func (c *ClientWithResponses) VisDeviceDeleteWithResponse(ctx context.Context, orgId int, body VisDeviceDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*VisDeviceDeleteResponse, error) {
	rsp, err := c.VisDeviceDelete(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVisDeviceDeleteResponse(rsp)
}

// VisExportIndexWithResponse request returning *VisExportIndexResponse
func (c *ClientWithResponses) VisExportIndexWithResponse(ctx context.Context, orgId int, params *VisExportIndexParams, reqEditors ...RequestEditorFn) (*VisExportIndexResponse, error) {
	rsp, err := c.VisExportIndex(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVisExportIndexResponse(rsp)
}

// VisExportDownloadWithResponse request returning *VisExportDownloadResponse
func (c *ClientWithResponses) VisExportDownloadWithResponse(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*VisExportDownloadResponse, error) {
	rsp, err := c.VisExportDownload(ctx, orgId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVisExportDownloadResponse(rsp)
}

// VisQueryCreateWithBodyWithResponse request with arbitrary body returning *VisQueryCreateResponse
func (c *ClientWithResponses) VisQueryCreateWithBodyWithResponse(ctx context.Context, orgId int, params *VisQueryCreateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VisQueryCreateResponse, error) {
	rsp, err := c.VisQueryCreateWithBody(ctx, orgId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVisQueryCreateResponse(rsp)
}

func (c *ClientWithResponses) VisQueryCreateWithResponse(ctx context.Context, orgId int, params *VisQueryCreateParams, body VisQueryCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*VisQueryCreateResponse, error) {
	rsp, err := c.VisQueryCreate(ctx, orgId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVisQueryCreateResponse(rsp)
}

// VisQueryShowWithResponse request returning *VisQueryShowResponse
func (c *ClientWithResponses) VisQueryShowWithResponse(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*VisQueryShowResponse, error) {
	rsp, err := c.VisQueryShow(ctx, orgId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVisQueryShowResponse(rsp)
}

// VisQueryDownloadWithResponse request returning *VisQueryDownloadResponse
func (c *ClientWithResponses) VisQueryDownloadWithResponse(ctx context.Context, orgId int, id string, params *VisQueryDownloadParams, reqEditors ...RequestEditorFn) (*VisQueryDownloadResponse, error) {
	rsp, err := c.VisQueryDownload(ctx, orgId, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVisQueryDownloadResponse(rsp)
}

// ParseVisDeviceEstimateDeleteResponse parses an HTTP response from a VisDeviceEstimateDeleteWithResponse call
func ParseVisDeviceEstimateDeleteResponse(rsp *http.Response) (*VisDeviceEstimateDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VisDeviceEstimateDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []VisFlexeraVisDeviceDeletionSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseVisDeviceDeleteResponse parses an HTTP response from a VisDeviceDeleteWithResponse call
func ParseVisDeviceDeleteResponse(rsp *http.Response) (*VisDeviceDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VisDeviceDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest []VisFlexeraVisDeviceDeletionSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}

// ParseVisExportIndexResponse parses an HTTP response from a VisExportIndexWithResponse call
func ParseVisExportIndexResponse(rsp *http.Response) (*VisExportIndexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VisExportIndexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VisExportFileList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseVisExportDownloadResponse parses an HTTP response from a VisExportDownloadWithResponse call
func ParseVisExportDownloadResponse(rsp *http.Response) (*VisExportDownloadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VisExportDownloadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseVisQueryCreateResponse parses an HTTP response from a VisQueryCreateWithResponse call
func ParseVisQueryCreateResponse(rsp *http.Response) (*VisQueryCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VisQueryCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VisCreateResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseVisQueryShowResponse parses an HTTP response from a VisQueryShowWithResponse call
func ParseVisQueryShowResponse(rsp *http.Response) (*VisQueryShowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VisQueryShowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VisQueryData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseVisQueryDownloadResponse parses an HTTP response from a VisQueryDownloadWithResponse call
func ParseVisQueryDownloadResponse(rsp *http.Response) (*VisQueryDownloadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VisQueryDownloadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
