// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 and cmd/split-client. DO NOT EDIT.

package flexera

import (
	"encoding/json"
	"fmt"
)

// Defines values for UobsGcpOnboardingUpdateRequestIncludeCostAndUsage.
const (
	False UobsGcpOnboardingUpdateRequestIncludeCostAndUsage = "false"
	True  UobsGcpOnboardingUpdateRequestIncludeCostAndUsage = "true"
)

// UobsGcpCostAndUsageCreateRequest defines model for Uobs_GcpCostAndUsageCreateRequest.
type UobsGcpCostAndUsageCreateRequest struct {
	// BillingDatasetId BigQuery dataset containing the billing export.
	BillingDatasetId string `json:"BillingDatasetId"`

	// BillingProjectId GCP project used for billing queries.
	BillingProjectId string `json:"BillingProjectId"`

	// GoogleGcsExportUri GCS URI of the billing export (e.g. gs://bucket/prefix/).
	GoogleGcsExportUri string `json:"GoogleGcsExportUri"`
}

// UobsGcpCostAndUsageUpdateRequest defines model for Uobs_GcpCostAndUsageUpdateRequest.
type UobsGcpCostAndUsageUpdateRequest struct {
	// GoogleGcsExportUri Updated GCS export URI.
	GoogleGcsExportUri *string `json:"GoogleGcsExportUri"`
}

// UobsGcpOnboardingCreateRequest defines model for Uobs_GcpOnboardingCreateRequest.
type UobsGcpOnboardingCreateRequest struct {
	// BillingAccountId GCP billing account ID.
	BillingAccountId string `json:"BillingAccountId"`

	// ConnectorName Connector name.
	ConnectorName string                           `json:"ConnectorName"`
	CostAndUsage  UobsGcpCostAndUsageCreateRequest `json:"CostAndUsage"`

	// IncludeCostAndUsage Must be 'true' for GCP Bill Connect.
	IncludeCostAndUsage string `json:"IncludeCostAndUsage"`

	// ServiceAccountKeyJson GCP service-account key JSON string.
	ServiceAccountKeyJson string `json:"ServiceAccountKeyJson"`
}

// UobsGcpOnboardingUpdateRequest defines model for Uobs_GcpOnboardingUpdateRequest.
type UobsGcpOnboardingUpdateRequest struct {
	// ConnectorName Connector name.
	ConnectorName *string                           `json:"ConnectorName"`
	CostAndUsage  *UobsGcpCostAndUsageUpdateRequest `json:"CostAndUsage,omitempty"`

	// IncludeCostAndUsage Include CCO flag.
	IncludeCostAndUsage *UobsGcpOnboardingUpdateRequestIncludeCostAndUsage `json:"IncludeCostAndUsage"`

	// ServiceAccountKeyJson Updated GCP service-account key JSON string.
	ServiceAccountKeyJson *string `json:"ServiceAccountKeyJson"`
}

// UobsGcpOnboardingUpdateRequestIncludeCostAndUsage Include CCO flag.
type UobsGcpOnboardingUpdateRequestIncludeCostAndUsage string

// UobsOnboardingCreateRequest defines model for Uobs_OnboardingCreateRequest.
type UobsOnboardingCreateRequest struct {
	// ConnectorName Human-readable connector name.
	ConnectorName string `json:"connectorName"`

	// Credentials Write-only secrets for the provider. Never returned on read.
	Credentials *map[string]interface{} `json:"credentials,omitempty"`

	// Provider Connector provider discriminator (e.g. n8n).
	Provider             string                 `json:"provider"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// UobsOnboardingUpdateRequest defines model for Uobs_OnboardingUpdateRequest.
type UobsOnboardingUpdateRequest struct {
	// ConnectorName Human-readable connector name.
	ConnectorName *string `json:"connectorName"`

	// Credentials Provide to rotate the stored secret(s). Write-only; never returned on read.
	Credentials *map[string]interface{} `json:"credentials"`

	// Provider Connector provider discriminator (e.g. n8n).
	Provider             string                 `json:"provider"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// UobsSaasConnectorRead defines model for Uobs_SaasConnectorRead.
type UobsSaasConnectorRead struct {
	// Config Non-secret, per-provider allow-listed configuration (e.g. instanceUrl, baseUrl, adminSubject, primaryDomain, clientId).
	Config *map[string]interface{} `json:"config,omitempty"`

	// ConnectorId Connector id (uuid).
	ConnectorId string `json:"connectorId"`

	// ConnectorName Human-readable connector name.
	ConnectorName string `json:"connectorName"`

	// CredentialId Primary credential id in the Flexera Credentials service.
	CredentialId string `json:"credentialId"`

	// EnrollmentStatus Enrollment status: ONBOARDED | IN-PROGRESS | FAILED | OFFBOARDED.
	EnrollmentStatus *string `json:"enrollmentStatus"`

	// LastRunAt ISO-8601 timestamp of the last execution; null if it has not run.
	LastRunAt *string `json:"lastRunAt"`

	// LastRunErrors Errors from the last execution (empty if none / not run).
	LastRunErrors *[]interface{} `json:"lastRunErrors,omitempty"`

	// LastRunStatus Status of the last data-retrieval execution (COMPLETED | FAILED | RUNNING | QUEUED); null if it has not run.
	LastRunStatus *string `json:"lastRunStatus"`

	// OffboardedAt ISO-8601 timestamp of soft-delete, if offboarded.
	OffboardedAt *string `json:"offboardedAt"`

	// OnboardedAt ISO-8601 timestamp of first onboarding.
	OnboardedAt *string `json:"onboardedAt"`

	// OrgId Flexera organization id.
	OrgId string `json:"orgId"`

	// Provider AICM provider discriminator, e.g. n8n.
	Provider string `json:"provider"`

	// SecondaryCredentialIds Map of secret-field name -> credential id for any secondary credentials.
	SecondaryCredentialIds *map[string]string `json:"secondaryCredentialIds,omitempty"`

	// UpdatedAt ISO-8601 timestamp of the last update.
	UpdatedAt *string `json:"updatedAt"`
}

// UobsValidationResult Verdict from the synchronous connection-test endpoint.
//
// Returned at HTTP 200 for every validation outcome (valid, rejected, vendor
// unreachable, vendor timeout) — the HTTP status reflects the call to us, the
// verdict lives here.
type UobsValidationResult struct {
	// Code On failure, the vendor's real HTTP status (e.g. 401/403), or 502 (could not reach the vendor) / 504 (vendor timed out). Absent on success.
	Code *int `json:"code"`

	// Detail On failure, the specific vendor/handler detail (secret-free). Absent on success.
	Detail *string `json:"detail"`

	// Reason On failure, a normalized human-readable message. Absent on success.
	Reason *string `json:"reason"`

	// Success True when the vendor accepted the submitted credentials.
	Success bool `json:"success"`
}

// Getter for additional properties for UobsOnboardingCreateRequest. Returns the specified
// element and whether it was found
func (a UobsOnboardingCreateRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for UobsOnboardingCreateRequest
func (a *UobsOnboardingCreateRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for UobsOnboardingCreateRequest to handle AdditionalProperties
func (a *UobsOnboardingCreateRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["connectorName"]; found {
		err = json.Unmarshal(raw, &a.ConnectorName)
		if err != nil {
			return fmt.Errorf("error reading 'connectorName': %w", err)
		}
		delete(object, "connectorName")
	}

	if raw, found := object["credentials"]; found {
		err = json.Unmarshal(raw, &a.Credentials)
		if err != nil {
			return fmt.Errorf("error reading 'credentials': %w", err)
		}
		delete(object, "credentials")
	}

	if raw, found := object["provider"]; found {
		err = json.Unmarshal(raw, &a.Provider)
		if err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
		delete(object, "provider")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for UobsOnboardingCreateRequest to handle AdditionalProperties
func (a UobsOnboardingCreateRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["connectorName"], err = json.Marshal(a.ConnectorName)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'connectorName': %w", err)
	}

	if a.Credentials != nil {
		object["credentials"], err = json.Marshal(a.Credentials)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'credentials': %w", err)
		}
	}

	object["provider"], err = json.Marshal(a.Provider)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'provider': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for UobsOnboardingUpdateRequest. Returns the specified
// element and whether it was found
func (a UobsOnboardingUpdateRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for UobsOnboardingUpdateRequest
func (a *UobsOnboardingUpdateRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for UobsOnboardingUpdateRequest to handle AdditionalProperties
func (a *UobsOnboardingUpdateRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["connectorName"]; found {
		err = json.Unmarshal(raw, &a.ConnectorName)
		if err != nil {
			return fmt.Errorf("error reading 'connectorName': %w", err)
		}
		delete(object, "connectorName")
	}

	if raw, found := object["credentials"]; found {
		err = json.Unmarshal(raw, &a.Credentials)
		if err != nil {
			return fmt.Errorf("error reading 'credentials': %w", err)
		}
		delete(object, "credentials")
	}

	if raw, found := object["provider"]; found {
		err = json.Unmarshal(raw, &a.Provider)
		if err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
		delete(object, "provider")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for UobsOnboardingUpdateRequest to handle AdditionalProperties
func (a UobsOnboardingUpdateRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ConnectorName != nil {
		object["connectorName"], err = json.Marshal(a.ConnectorName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'connectorName': %w", err)
		}
	}

	if a.Credentials != nil {
		object["credentials"], err = json.Marshal(a.Credentials)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'credentials': %w", err)
		}
	}

	object["provider"], err = json.Marshal(a.Provider)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'provider': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
