// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 and cmd/split-client. DO NOT EDIT.

package flexera

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	"io"
	"net/http"
	"net/url"
)

// Defines values for BillUploadBillUploadCreateOperationRequestBodyOperation.
const (
	Abort  BillUploadBillUploadCreateOperationRequestBodyOperation = "abort"
	Commit BillUploadBillUploadCreateOperationRequestBodyOperation = "commit"
)

// BillUploadBillUploadCreateOperationRequestBody defines model for BillUpload_BillUploadCreateOperationRequestBody.
type BillUploadBillUploadCreateOperationRequestBody struct {
	// Operation The type of operation to perform on this bill upload, ie commit or abort
	Operation BillUploadBillUploadCreateOperationRequestBodyOperation `json:"operation"`
}

// BillUploadBillUploadCreateOperationRequestBodyOperation The type of operation to perform on this bill upload, ie commit or abort
type BillUploadBillUploadCreateOperationRequestBodyOperation string

// BillUploadBillUploadCreateRequestBody defines model for BillUpload_BillUploadCreateRequestBody.
type BillUploadBillUploadCreateRequestBody struct {
	// BillConnectId The bill connect to use for this bill upload
	BillConnectId string `json:"billConnectId"`

	// BillingPeriod The billing period covered by this bill upload, formatted as yyyy-mm
	BillingPeriod string `json:"billingPeriod"`
}

// BillUploadBillUploadIndexParams defines parameters for BillUploadBillUploadIndex.
type BillUploadBillUploadIndexParams struct {
	// BillingPeriod Optional filter by billing period
	BillingPeriod *string `form:"billingPeriod,omitempty" json:"billingPeriod,omitempty"`

	// BillConnectId Optional filter by bill connect ID
	BillConnectId *string `form:"billConnectId,omitempty" json:"billConnectId,omitempty"`
}

// BillUploadBillUploadCreateJSONRequestBody defines body for BillUploadBillUploadCreate for application/json ContentType.
type BillUploadBillUploadCreateJSONRequestBody = BillUploadBillUploadCreateRequestBody

// BillUploadBillUploadCreateOperationJSONRequestBody defines body for BillUploadBillUploadCreateOperation for application/json ContentType.
type BillUploadBillUploadCreateOperationJSONRequestBody = BillUploadBillUploadCreateOperationRequestBody

func (c *Client) BillUploadBillUploadIndex(ctx context.Context, orgId int, params *BillUploadBillUploadIndexParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBillUploadBillUploadIndexRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BillUploadBillUploadCreateWithBody(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBillUploadBillUploadCreateRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BillUploadBillUploadCreate(ctx context.Context, orgId int, body BillUploadBillUploadCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBillUploadBillUploadCreateRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BillUploadBillUploadDelete(ctx context.Context, orgId int, billUploadId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBillUploadBillUploadDeleteRequest(c.Server, orgId, billUploadId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BillUploadBillUploadShow(ctx context.Context, orgId int, billUploadId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBillUploadBillUploadShowRequest(c.Server, orgId, billUploadId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BillUploadBillUploadCreateFileWithBody(ctx context.Context, orgId int, billUploadId openapi_types.UUID, fileId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBillUploadBillUploadCreateFileRequestWithBody(c.Server, orgId, billUploadId, fileId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BillUploadBillUploadCreateOperationWithBody(ctx context.Context, orgId int, billUploadId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBillUploadBillUploadCreateOperationRequestWithBody(c.Server, orgId, billUploadId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BillUploadBillUploadCreateOperation(ctx context.Context, orgId int, billUploadId openapi_types.UUID, body BillUploadBillUploadCreateOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBillUploadBillUploadCreateOperationRequest(c.Server, orgId, billUploadId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewBillUploadBillUploadIndexRequest generates requests for BillUploadBillUploadIndex
func NewBillUploadBillUploadIndexRequest(server string, orgId int, params *BillUploadBillUploadIndexParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/optima/orgs/%s/billUploads", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.BillingPeriod != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "billingPeriod", runtime.ParamLocationQuery, *params.BillingPeriod); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.BillConnectId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "billConnectId", runtime.ParamLocationQuery, *params.BillConnectId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBillUploadBillUploadCreateRequest calls the generic BillUploadBillUploadCreate builder with application/json body
func NewBillUploadBillUploadCreateRequest(server string, orgId int, body BillUploadBillUploadCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBillUploadBillUploadCreateRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewBillUploadBillUploadCreateRequestWithBody generates requests for BillUploadBillUploadCreate with any type of body
func NewBillUploadBillUploadCreateRequestWithBody(server string, orgId int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/optima/orgs/%s/billUploads", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewBillUploadBillUploadDeleteRequest generates requests for BillUploadBillUploadDelete
func NewBillUploadBillUploadDeleteRequest(server string, orgId int, billUploadId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "billUploadId", runtime.ParamLocationPath, billUploadId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/optima/orgs/%s/billUploads/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBillUploadBillUploadShowRequest generates requests for BillUploadBillUploadShow
func NewBillUploadBillUploadShowRequest(server string, orgId int, billUploadId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "billUploadId", runtime.ParamLocationPath, billUploadId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/optima/orgs/%s/billUploads/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBillUploadBillUploadCreateFileRequestWithBody generates requests for BillUploadBillUploadCreateFile with any type of body
func NewBillUploadBillUploadCreateFileRequestWithBody(server string, orgId int, billUploadId openapi_types.UUID, fileId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "billUploadId", runtime.ParamLocationPath, billUploadId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "fileId", runtime.ParamLocationPath, fileId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/optima/orgs/%s/billUploads/%s/files/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewBillUploadBillUploadCreateOperationRequest calls the generic BillUploadBillUploadCreateOperation builder with application/json body
func NewBillUploadBillUploadCreateOperationRequest(server string, orgId int, billUploadId openapi_types.UUID, body BillUploadBillUploadCreateOperationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBillUploadBillUploadCreateOperationRequestWithBody(server, orgId, billUploadId, "application/json", bodyReader)
}

// NewBillUploadBillUploadCreateOperationRequestWithBody generates requests for BillUploadBillUploadCreateOperation with any type of body
func NewBillUploadBillUploadCreateOperationRequestWithBody(server string, orgId int, billUploadId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "billUploadId", runtime.ParamLocationPath, billUploadId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/optima/orgs/%s/billUploads/%s/operations", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}
