// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 and cmd/split-client. DO NOT EDIT.

package flexera

import (
	"context"
	"encoding/json"
	openapi_types "github.com/oapi-codegen/runtime/types"
	"io"
	"net/http"
	"strings"
)

// FinopsCustomizationsSavedFiltersshowResponseBody defines model for FinopsCustomizations_SavedFiltersshowResponseBody.
type FinopsCustomizationsSavedFiltersshowResponseBody = FinopsCustomizationsSavedFilterHTTPBody

type FinopsCustomizationsReportSubscriptionsIndexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsReportSubscriptionList
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsReportSubscriptionsIndexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsReportSubscriptionsIndexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsReportSubscriptionsCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *FinopsCustomizationsReportSubscriptionResult
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsReportSubscriptionsCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsReportSubscriptionsCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsReportSubscriptionsDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsReportSubscriptionsDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsReportSubscriptionsDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsReportSubscriptionsShowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsReportSubscriptionResult
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsReportSubscriptionsShowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsReportSubscriptionsShowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsReportSubscriptionsUpdateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsReportSubscriptionResult
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsReportSubscriptionsUpdateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsReportSubscriptionsUpdateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsRuleBasedDimensionIndexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsRuleBasedDimensionList
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsRuleBasedDimensionIndexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsRuleBasedDimensionIndexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsFlexeraFinopsCustomizationsRuleBasedDimension
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsRuleBasedDimensionRulesListDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsRuleBasedDimensionRulesListDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsRuleBasedDimensionRulesListDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsRuleBasedDimensionRulesListShowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsRuleBasedDimensionRuleList
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsRuleBasedDimensionRulesListShowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsRuleBasedDimensionRulesListShowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsRuleBasedDimensionSummary
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsSavedFiltersIndexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsIndexSavedFiltersResult
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsSavedFiltersIndexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsSavedFiltersIndexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsSavedFiltersCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *FinopsCustomizationsSavedFilterHTTPBody
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsSavedFiltersCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsSavedFiltersCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsSavedFiltersDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsSavedFiltersDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsSavedFiltersDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsSavedFiltersShowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsSavedFiltersshowResponseBody
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsSavedFiltersShowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsSavedFiltersShowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsSavedFiltersPatchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsSavedFilterHTTPBody
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsSavedFiltersPatchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsSavedFiltersPatchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsSavedFiltersUpdateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsSavedFilterHTTPBody
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsSavedFiltersUpdateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsSavedFiltersUpdateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsTagDimensionIndexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsTagDimensionList
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsTagDimensionIndexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsTagDimensionIndexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsTagDimensionCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *FinopsCustomizationsFlexeraFinopsCustomizationsTagDimension
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsTagDimensionCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsTagDimensionCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsTagDimensionDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsTagDimensionDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsTagDimensionDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsTagDimensionShowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsFlexeraFinopsCustomizationsTagDimension
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsTagDimensionShowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsTagDimensionShowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinopsCustomizationsTagDimensionUpdateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FinopsCustomizationsFlexeraFinopsCustomizationsTagDimension
}

// Status returns HTTPResponse.Status
func (r FinopsCustomizationsTagDimensionUpdateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinopsCustomizationsTagDimensionUpdateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// FinopsCustomizationsReportSubscriptionsIndexWithResponse request returning *FinopsCustomizationsReportSubscriptionsIndexResponse
func (c *ClientWithResponses) FinopsCustomizationsReportSubscriptionsIndexWithResponse(ctx context.Context, orgId int, params *FinopsCustomizationsReportSubscriptionsIndexParams, reqEditors ...RequestEditorFn) (*FinopsCustomizationsReportSubscriptionsIndexResponse, error) {
	rsp, err := c.FinopsCustomizationsReportSubscriptionsIndex(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsReportSubscriptionsIndexResponse(rsp)
}

// FinopsCustomizationsReportSubscriptionsCreateWithBodyWithResponse request with arbitrary body returning *FinopsCustomizationsReportSubscriptionsCreateResponse
func (c *ClientWithResponses) FinopsCustomizationsReportSubscriptionsCreateWithBodyWithResponse(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinopsCustomizationsReportSubscriptionsCreateResponse, error) {
	rsp, err := c.FinopsCustomizationsReportSubscriptionsCreateWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsReportSubscriptionsCreateResponse(rsp)
}

func (c *ClientWithResponses) FinopsCustomizationsReportSubscriptionsCreateWithResponse(ctx context.Context, orgId int, body FinopsCustomizationsReportSubscriptionsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*FinopsCustomizationsReportSubscriptionsCreateResponse, error) {
	rsp, err := c.FinopsCustomizationsReportSubscriptionsCreate(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsReportSubscriptionsCreateResponse(rsp)
}

// FinopsCustomizationsReportSubscriptionsDeleteWithResponse request returning *FinopsCustomizationsReportSubscriptionsDeleteResponse
func (c *ClientWithResponses) FinopsCustomizationsReportSubscriptionsDeleteWithResponse(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsReportSubscriptionsDeleteParams, reqEditors ...RequestEditorFn) (*FinopsCustomizationsReportSubscriptionsDeleteResponse, error) {
	rsp, err := c.FinopsCustomizationsReportSubscriptionsDelete(ctx, orgId, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsReportSubscriptionsDeleteResponse(rsp)
}

// FinopsCustomizationsReportSubscriptionsShowWithResponse request returning *FinopsCustomizationsReportSubscriptionsShowResponse
func (c *ClientWithResponses) FinopsCustomizationsReportSubscriptionsShowWithResponse(ctx context.Context, orgId int, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*FinopsCustomizationsReportSubscriptionsShowResponse, error) {
	rsp, err := c.FinopsCustomizationsReportSubscriptionsShow(ctx, orgId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsReportSubscriptionsShowResponse(rsp)
}

// FinopsCustomizationsReportSubscriptionsUpdateWithBodyWithResponse request with arbitrary body returning *FinopsCustomizationsReportSubscriptionsUpdateResponse
func (c *ClientWithResponses) FinopsCustomizationsReportSubscriptionsUpdateWithBodyWithResponse(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsReportSubscriptionsUpdateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinopsCustomizationsReportSubscriptionsUpdateResponse, error) {
	rsp, err := c.FinopsCustomizationsReportSubscriptionsUpdateWithBody(ctx, orgId, id, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsReportSubscriptionsUpdateResponse(rsp)
}

func (c *ClientWithResponses) FinopsCustomizationsReportSubscriptionsUpdateWithResponse(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsReportSubscriptionsUpdateParams, body FinopsCustomizationsReportSubscriptionsUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*FinopsCustomizationsReportSubscriptionsUpdateResponse, error) {
	rsp, err := c.FinopsCustomizationsReportSubscriptionsUpdate(ctx, orgId, id, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsReportSubscriptionsUpdateResponse(rsp)
}

// FinopsCustomizationsRuleBasedDimensionIndexWithResponse request returning *FinopsCustomizationsRuleBasedDimensionIndexResponse
func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionIndexWithResponse(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionIndexResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionIndex(ctx, orgId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionIndexResponse(rsp)
}

// FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteWithResponse request returning *FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteResponse
func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteWithResponse(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDelete(ctx, orgId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteResponse(rsp)
}

// FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowWithResponse request returning *FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowResponse
func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowWithResponse(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShow(ctx, orgId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowResponse(rsp)
}

// FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateWithBodyWithResponse request with arbitrary body returning *FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse
func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateWithBodyWithResponse(ctx context.Context, orgId int, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateWithBody(ctx, orgId, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse(rsp)
}

func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateWithResponse(ctx context.Context, orgId int, id string, body FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdate(ctx, orgId, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse(rsp)
}

// FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateWithBodyWithResponse request with arbitrary body returning *FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse
func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateWithBodyWithResponse(ctx context.Context, orgId int, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateWithBody(ctx, orgId, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse(rsp)
}

func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateWithResponse(ctx context.Context, orgId int, id string, body FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreate(ctx, orgId, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse(rsp)
}

// FinopsCustomizationsRuleBasedDimensionRulesListDeleteWithResponse request returning *FinopsCustomizationsRuleBasedDimensionRulesListDeleteResponse
func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionRulesListDeleteWithResponse(ctx context.Context, orgId int, id string, effectiveAt string, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionRulesListDeleteResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionRulesListDelete(ctx, orgId, id, effectiveAt, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionRulesListDeleteResponse(rsp)
}

// FinopsCustomizationsRuleBasedDimensionRulesListShowWithResponse request returning *FinopsCustomizationsRuleBasedDimensionRulesListShowResponse
func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionRulesListShowWithResponse(ctx context.Context, orgId int, id string, effectiveAt string, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionRulesListShowResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionRulesListShow(ctx, orgId, id, effectiveAt, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionRulesListShowResponse(rsp)
}

// FinopsCustomizationsRuleBasedDimensionRulesListReplaceWithBodyWithResponse request with arbitrary body returning *FinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse
func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionRulesListReplaceWithBodyWithResponse(ctx context.Context, orgId int, id string, effectiveAt string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionRulesListReplaceWithBody(ctx, orgId, id, effectiveAt, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse(rsp)
}

func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionRulesListReplaceWithResponse(ctx context.Context, orgId int, id string, effectiveAt string, body FinopsCustomizationsRuleBasedDimensionRulesListReplaceJSONRequestBody, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionRulesListReplace(ctx, orgId, id, effectiveAt, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse(rsp)
}

// FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowWithResponse request returning *FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowResponse
func (c *ClientWithResponses) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowWithResponse(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowResponse, error) {
	rsp, err := c.FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShow(ctx, orgId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowResponse(rsp)
}

// FinopsCustomizationsSavedFiltersIndexWithResponse request returning *FinopsCustomizationsSavedFiltersIndexResponse
func (c *ClientWithResponses) FinopsCustomizationsSavedFiltersIndexWithResponse(ctx context.Context, orgId int, params *FinopsCustomizationsSavedFiltersIndexParams, reqEditors ...RequestEditorFn) (*FinopsCustomizationsSavedFiltersIndexResponse, error) {
	rsp, err := c.FinopsCustomizationsSavedFiltersIndex(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsSavedFiltersIndexResponse(rsp)
}

// FinopsCustomizationsSavedFiltersCreateWithBodyWithResponse request with arbitrary body returning *FinopsCustomizationsSavedFiltersCreateResponse
func (c *ClientWithResponses) FinopsCustomizationsSavedFiltersCreateWithBodyWithResponse(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinopsCustomizationsSavedFiltersCreateResponse, error) {
	rsp, err := c.FinopsCustomizationsSavedFiltersCreateWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsSavedFiltersCreateResponse(rsp)
}

func (c *ClientWithResponses) FinopsCustomizationsSavedFiltersCreateWithResponse(ctx context.Context, orgId int, body FinopsCustomizationsSavedFiltersCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*FinopsCustomizationsSavedFiltersCreateResponse, error) {
	rsp, err := c.FinopsCustomizationsSavedFiltersCreate(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsSavedFiltersCreateResponse(rsp)
}

// FinopsCustomizationsSavedFiltersDeleteWithResponse request returning *FinopsCustomizationsSavedFiltersDeleteResponse
func (c *ClientWithResponses) FinopsCustomizationsSavedFiltersDeleteWithResponse(ctx context.Context, orgId int, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*FinopsCustomizationsSavedFiltersDeleteResponse, error) {
	rsp, err := c.FinopsCustomizationsSavedFiltersDelete(ctx, orgId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsSavedFiltersDeleteResponse(rsp)
}

// FinopsCustomizationsSavedFiltersShowWithResponse request returning *FinopsCustomizationsSavedFiltersShowResponse
func (c *ClientWithResponses) FinopsCustomizationsSavedFiltersShowWithResponse(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersShowParams, reqEditors ...RequestEditorFn) (*FinopsCustomizationsSavedFiltersShowResponse, error) {
	rsp, err := c.FinopsCustomizationsSavedFiltersShow(ctx, orgId, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsSavedFiltersShowResponse(rsp)
}

// FinopsCustomizationsSavedFiltersPatchWithBodyWithResponse request with arbitrary body returning *FinopsCustomizationsSavedFiltersPatchResponse
func (c *ClientWithResponses) FinopsCustomizationsSavedFiltersPatchWithBodyWithResponse(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersPatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinopsCustomizationsSavedFiltersPatchResponse, error) {
	rsp, err := c.FinopsCustomizationsSavedFiltersPatchWithBody(ctx, orgId, id, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsSavedFiltersPatchResponse(rsp)
}

func (c *ClientWithResponses) FinopsCustomizationsSavedFiltersPatchWithResponse(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersPatchParams, body FinopsCustomizationsSavedFiltersPatchJSONRequestBody, reqEditors ...RequestEditorFn) (*FinopsCustomizationsSavedFiltersPatchResponse, error) {
	rsp, err := c.FinopsCustomizationsSavedFiltersPatch(ctx, orgId, id, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsSavedFiltersPatchResponse(rsp)
}

// FinopsCustomizationsSavedFiltersUpdateWithBodyWithResponse request with arbitrary body returning *FinopsCustomizationsSavedFiltersUpdateResponse
func (c *ClientWithResponses) FinopsCustomizationsSavedFiltersUpdateWithBodyWithResponse(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersUpdateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinopsCustomizationsSavedFiltersUpdateResponse, error) {
	rsp, err := c.FinopsCustomizationsSavedFiltersUpdateWithBody(ctx, orgId, id, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsSavedFiltersUpdateResponse(rsp)
}

func (c *ClientWithResponses) FinopsCustomizationsSavedFiltersUpdateWithResponse(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersUpdateParams, body FinopsCustomizationsSavedFiltersUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*FinopsCustomizationsSavedFiltersUpdateResponse, error) {
	rsp, err := c.FinopsCustomizationsSavedFiltersUpdate(ctx, orgId, id, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsSavedFiltersUpdateResponse(rsp)
}

// FinopsCustomizationsTagDimensionIndexWithResponse request returning *FinopsCustomizationsTagDimensionIndexResponse
func (c *ClientWithResponses) FinopsCustomizationsTagDimensionIndexWithResponse(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*FinopsCustomizationsTagDimensionIndexResponse, error) {
	rsp, err := c.FinopsCustomizationsTagDimensionIndex(ctx, orgId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsTagDimensionIndexResponse(rsp)
}

// FinopsCustomizationsTagDimensionCreateWithBodyWithResponse request with arbitrary body returning *FinopsCustomizationsTagDimensionCreateResponse
func (c *ClientWithResponses) FinopsCustomizationsTagDimensionCreateWithBodyWithResponse(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinopsCustomizationsTagDimensionCreateResponse, error) {
	rsp, err := c.FinopsCustomizationsTagDimensionCreateWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsTagDimensionCreateResponse(rsp)
}

func (c *ClientWithResponses) FinopsCustomizationsTagDimensionCreateWithResponse(ctx context.Context, orgId int, body FinopsCustomizationsTagDimensionCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*FinopsCustomizationsTagDimensionCreateResponse, error) {
	rsp, err := c.FinopsCustomizationsTagDimensionCreate(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsTagDimensionCreateResponse(rsp)
}

// FinopsCustomizationsTagDimensionDeleteWithResponse request returning *FinopsCustomizationsTagDimensionDeleteResponse
func (c *ClientWithResponses) FinopsCustomizationsTagDimensionDeleteWithResponse(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*FinopsCustomizationsTagDimensionDeleteResponse, error) {
	rsp, err := c.FinopsCustomizationsTagDimensionDelete(ctx, orgId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsTagDimensionDeleteResponse(rsp)
}

// FinopsCustomizationsTagDimensionShowWithResponse request returning *FinopsCustomizationsTagDimensionShowResponse
func (c *ClientWithResponses) FinopsCustomizationsTagDimensionShowWithResponse(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*FinopsCustomizationsTagDimensionShowResponse, error) {
	rsp, err := c.FinopsCustomizationsTagDimensionShow(ctx, orgId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsTagDimensionShowResponse(rsp)
}

// FinopsCustomizationsTagDimensionUpdateWithBodyWithResponse request with arbitrary body returning *FinopsCustomizationsTagDimensionUpdateResponse
func (c *ClientWithResponses) FinopsCustomizationsTagDimensionUpdateWithBodyWithResponse(ctx context.Context, orgId int, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinopsCustomizationsTagDimensionUpdateResponse, error) {
	rsp, err := c.FinopsCustomizationsTagDimensionUpdateWithBody(ctx, orgId, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsTagDimensionUpdateResponse(rsp)
}

func (c *ClientWithResponses) FinopsCustomizationsTagDimensionUpdateWithResponse(ctx context.Context, orgId int, id string, body FinopsCustomizationsTagDimensionUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*FinopsCustomizationsTagDimensionUpdateResponse, error) {
	rsp, err := c.FinopsCustomizationsTagDimensionUpdate(ctx, orgId, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinopsCustomizationsTagDimensionUpdateResponse(rsp)
}

// ParseFinopsCustomizationsReportSubscriptionsIndexResponse parses an HTTP response from a FinopsCustomizationsReportSubscriptionsIndexWithResponse call
func ParseFinopsCustomizationsReportSubscriptionsIndexResponse(rsp *http.Response) (*FinopsCustomizationsReportSubscriptionsIndexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsReportSubscriptionsIndexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsReportSubscriptionList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsReportSubscriptionsCreateResponse parses an HTTP response from a FinopsCustomizationsReportSubscriptionsCreateWithResponse call
func ParseFinopsCustomizationsReportSubscriptionsCreateResponse(rsp *http.Response) (*FinopsCustomizationsReportSubscriptionsCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsReportSubscriptionsCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest FinopsCustomizationsReportSubscriptionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsReportSubscriptionsDeleteResponse parses an HTTP response from a FinopsCustomizationsReportSubscriptionsDeleteWithResponse call
func ParseFinopsCustomizationsReportSubscriptionsDeleteResponse(rsp *http.Response) (*FinopsCustomizationsReportSubscriptionsDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsReportSubscriptionsDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFinopsCustomizationsReportSubscriptionsShowResponse parses an HTTP response from a FinopsCustomizationsReportSubscriptionsShowWithResponse call
func ParseFinopsCustomizationsReportSubscriptionsShowResponse(rsp *http.Response) (*FinopsCustomizationsReportSubscriptionsShowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsReportSubscriptionsShowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsReportSubscriptionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsReportSubscriptionsUpdateResponse parses an HTTP response from a FinopsCustomizationsReportSubscriptionsUpdateWithResponse call
func ParseFinopsCustomizationsReportSubscriptionsUpdateResponse(rsp *http.Response) (*FinopsCustomizationsReportSubscriptionsUpdateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsReportSubscriptionsUpdateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsReportSubscriptionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsRuleBasedDimensionIndexResponse parses an HTTP response from a FinopsCustomizationsRuleBasedDimensionIndexWithResponse call
func ParseFinopsCustomizationsRuleBasedDimensionIndexResponse(rsp *http.Response) (*FinopsCustomizationsRuleBasedDimensionIndexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsRuleBasedDimensionIndexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsRuleBasedDimensionList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteResponse parses an HTTP response from a FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteWithResponse call
func ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteResponse(rsp *http.Response) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowResponse parses an HTTP response from a FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowWithResponse call
func ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowResponse(rsp *http.Response) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsFlexeraFinopsCustomizationsRuleBasedDimension
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse parses an HTTP response from a FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateWithResponse call
func ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse(rsp *http.Response) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse parses an HTTP response from a FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateWithResponse call
func ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse(rsp *http.Response) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFinopsCustomizationsRuleBasedDimensionRulesListDeleteResponse parses an HTTP response from a FinopsCustomizationsRuleBasedDimensionRulesListDeleteWithResponse call
func ParseFinopsCustomizationsRuleBasedDimensionRulesListDeleteResponse(rsp *http.Response) (*FinopsCustomizationsRuleBasedDimensionRulesListDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsRuleBasedDimensionRulesListDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFinopsCustomizationsRuleBasedDimensionRulesListShowResponse parses an HTTP response from a FinopsCustomizationsRuleBasedDimensionRulesListShowWithResponse call
func ParseFinopsCustomizationsRuleBasedDimensionRulesListShowResponse(rsp *http.Response) (*FinopsCustomizationsRuleBasedDimensionRulesListShowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsRuleBasedDimensionRulesListShowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsRuleBasedDimensionRuleList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse parses an HTTP response from a FinopsCustomizationsRuleBasedDimensionRulesListReplaceWithResponse call
func ParseFinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse(rsp *http.Response) (*FinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsRuleBasedDimensionRulesListReplaceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowResponse parses an HTTP response from a FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowWithResponse call
func ParseFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowResponse(rsp *http.Response) (*FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsRuleBasedDimensionSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsSavedFiltersIndexResponse parses an HTTP response from a FinopsCustomizationsSavedFiltersIndexWithResponse call
func ParseFinopsCustomizationsSavedFiltersIndexResponse(rsp *http.Response) (*FinopsCustomizationsSavedFiltersIndexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsSavedFiltersIndexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsIndexSavedFiltersResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsSavedFiltersCreateResponse parses an HTTP response from a FinopsCustomizationsSavedFiltersCreateWithResponse call
func ParseFinopsCustomizationsSavedFiltersCreateResponse(rsp *http.Response) (*FinopsCustomizationsSavedFiltersCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsSavedFiltersCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest FinopsCustomizationsSavedFilterHTTPBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsSavedFiltersDeleteResponse parses an HTTP response from a FinopsCustomizationsSavedFiltersDeleteWithResponse call
func ParseFinopsCustomizationsSavedFiltersDeleteResponse(rsp *http.Response) (*FinopsCustomizationsSavedFiltersDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsSavedFiltersDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFinopsCustomizationsSavedFiltersShowResponse parses an HTTP response from a FinopsCustomizationsSavedFiltersShowWithResponse call
func ParseFinopsCustomizationsSavedFiltersShowResponse(rsp *http.Response) (*FinopsCustomizationsSavedFiltersShowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsSavedFiltersShowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsSavedFiltersshowResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsSavedFiltersPatchResponse parses an HTTP response from a FinopsCustomizationsSavedFiltersPatchWithResponse call
func ParseFinopsCustomizationsSavedFiltersPatchResponse(rsp *http.Response) (*FinopsCustomizationsSavedFiltersPatchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsSavedFiltersPatchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsSavedFilterHTTPBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsSavedFiltersUpdateResponse parses an HTTP response from a FinopsCustomizationsSavedFiltersUpdateWithResponse call
func ParseFinopsCustomizationsSavedFiltersUpdateResponse(rsp *http.Response) (*FinopsCustomizationsSavedFiltersUpdateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsSavedFiltersUpdateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsSavedFilterHTTPBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsTagDimensionIndexResponse parses an HTTP response from a FinopsCustomizationsTagDimensionIndexWithResponse call
func ParseFinopsCustomizationsTagDimensionIndexResponse(rsp *http.Response) (*FinopsCustomizationsTagDimensionIndexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsTagDimensionIndexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsTagDimensionList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsTagDimensionCreateResponse parses an HTTP response from a FinopsCustomizationsTagDimensionCreateWithResponse call
func ParseFinopsCustomizationsTagDimensionCreateResponse(rsp *http.Response) (*FinopsCustomizationsTagDimensionCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsTagDimensionCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest FinopsCustomizationsFlexeraFinopsCustomizationsTagDimension
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsTagDimensionDeleteResponse parses an HTTP response from a FinopsCustomizationsTagDimensionDeleteWithResponse call
func ParseFinopsCustomizationsTagDimensionDeleteResponse(rsp *http.Response) (*FinopsCustomizationsTagDimensionDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsTagDimensionDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFinopsCustomizationsTagDimensionShowResponse parses an HTTP response from a FinopsCustomizationsTagDimensionShowWithResponse call
func ParseFinopsCustomizationsTagDimensionShowResponse(rsp *http.Response) (*FinopsCustomizationsTagDimensionShowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsTagDimensionShowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsFlexeraFinopsCustomizationsTagDimension
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinopsCustomizationsTagDimensionUpdateResponse parses an HTTP response from a FinopsCustomizationsTagDimensionUpdateWithResponse call
func ParseFinopsCustomizationsTagDimensionUpdateResponse(rsp *http.Response) (*FinopsCustomizationsTagDimensionUpdateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinopsCustomizationsTagDimensionUpdateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FinopsCustomizationsFlexeraFinopsCustomizationsTagDimension
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
