// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 and cmd/split-client. DO NOT EDIT.

package flexera

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strings"
)

// UobsErrorResponse defines model for Uobs_ErrorResponse.
type UobsErrorResponse struct {
	Fault     *bool  `json:"fault,omitempty"`
	Id        string `json:"id"`
	Message   string `json:"message"`
	Name      string `json:"name"`
	Temporary *bool  `json:"temporary,omitempty"`
	Timeout   *bool  `json:"timeout,omitempty"`
}

// UobsOkResponseAny defines model for Uobs_OkResponse_Any_.
type UobsOkResponseAny struct {
	Kind   *string        `json:"kind"`
	Values *[]interface{} `json:"values"`
}

// UobsOkResponseSaasConnectorRead defines model for Uobs_OkResponse_SaasConnectorRead_.
type UobsOkResponseSaasConnectorRead struct {
	Kind   *string                  `json:"kind"`
	Values *[]UobsSaasConnectorRead `json:"values"`
}

// UobsOkResponseValidationResult defines model for Uobs_OkResponse_ValidationResult_.
type UobsOkResponseValidationResult struct {
	Kind   *string                 `json:"kind"`
	Values *[]UobsValidationResult `json:"values"`
}

type UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UobsOkResponseSaasConnectorRead
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UobsOkResponseSaasConnectorRead
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UobsOkResponseValidationResult
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *UobsOkResponseAny
	JSON400      *UobsErrorResponse
	JSON401      *UobsErrorResponse
	JSON403      *UobsErrorResponse
	JSON404      *UobsErrorResponse
	JSON429      *UobsErrorResponse
	JSON500      *UobsErrorResponse
	JSON502      *UobsErrorResponse
}

// Status returns HTTPResponse.Status
func (r UobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetWithResponse request returning *UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetResponse
func (c *ClientWithResponses) UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetWithResponse(ctx context.Context, orgId string, params *UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetParams, reqEditors ...RequestEditorFn) (*UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetResponse, error) {
	rsp, err := c.UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGet(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetResponse(rsp)
}

// UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetWithResponse request returning *UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetResponse
func (c *ClientWithResponses) UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetWithResponse(ctx context.Context, orgId string, reqEditors ...RequestEditorFn) (*UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetResponse, error) {
	rsp, err := c.UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGet(ctx, orgId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetResponse(rsp)
}

// UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetWithResponse request returning *UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetResponse
func (c *ClientWithResponses) UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetWithResponse(ctx context.Context, orgId string, params *UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetParams, reqEditors ...RequestEditorFn) (*UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetResponse, error) {
	rsp, err := c.UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGet(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetResponse(rsp)
}

// UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetWithResponse request returning *UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetResponse
func (c *ClientWithResponses) UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetWithResponse(ctx context.Context, orgId string, identifier string, reqEditors ...RequestEditorFn) (*UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetResponse, error) {
	rsp, err := c.UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGet(ctx, orgId, identifier, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetResponse(rsp)
}

// UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteWithResponse request returning *UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteResponse
func (c *ClientWithResponses) UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteWithResponse(ctx context.Context, orgId string, params *UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteParams, reqEditors ...RequestEditorFn) (*UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteResponse, error) {
	rsp, err := c.UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDelete(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteResponse(rsp)
}

// UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostWithBodyWithResponse request with arbitrary body returning *UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse
func (c *ClientWithResponses) UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostWithBodyWithResponse(ctx context.Context, orgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse, error) {
	rsp, err := c.UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse(rsp)
}

func (c *ClientWithResponses) UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostWithResponse(ctx context.Context, orgId string, body UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostJSONRequestBody, reqEditors ...RequestEditorFn) (*UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse, error) {
	rsp, err := c.UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPost(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse(rsp)
}

// UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutWithBodyWithResponse request with arbitrary body returning *UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse
func (c *ClientWithResponses) UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutWithBodyWithResponse(ctx context.Context, orgId string, connectorId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse, error) {
	rsp, err := c.UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutWithBody(ctx, orgId, connectorId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse(rsp)
}

func (c *ClientWithResponses) UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutWithResponse(ctx context.Context, orgId string, connectorId string, body UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutJSONRequestBody, reqEditors ...RequestEditorFn) (*UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse, error) {
	rsp, err := c.UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPut(ctx, orgId, connectorId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse(rsp)
}

// UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetWithResponse request returning *UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetResponse
func (c *ClientWithResponses) UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetWithResponse(ctx context.Context, orgId string, params *UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetParams, reqEditors ...RequestEditorFn) (*UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetResponse, error) {
	rsp, err := c.UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGet(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetResponse(rsp)
}

// UobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetWithResponse request returning *UobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetResponse
func (c *ClientWithResponses) UobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetWithResponse(ctx context.Context, orgId string, reqEditors ...RequestEditorFn) (*UobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetResponse, error) {
	rsp, err := c.UobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGet(ctx, orgId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetResponse(rsp)
}

// UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetWithResponse request returning *UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetResponse
func (c *ClientWithResponses) UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetWithResponse(ctx context.Context, orgId string, params *UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetParams, reqEditors ...RequestEditorFn) (*UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetResponse, error) {
	rsp, err := c.UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGet(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetResponse(rsp)
}

// UobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetWithResponse request returning *UobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetResponse
func (c *ClientWithResponses) UobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetWithResponse(ctx context.Context, orgId string, identifier string, reqEditors ...RequestEditorFn) (*UobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetResponse, error) {
	rsp, err := c.UobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGet(ctx, orgId, identifier, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetResponse(rsp)
}

// UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostWithBodyWithResponse request with arbitrary body returning *UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse
func (c *ClientWithResponses) UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostWithBodyWithResponse(ctx context.Context, orgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse, error) {
	rsp, err := c.UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse(rsp)
}

func (c *ClientWithResponses) UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostWithResponse(ctx context.Context, orgId string, body UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostJSONRequestBody, reqEditors ...RequestEditorFn) (*UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse, error) {
	rsp, err := c.UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPost(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse(rsp)
}

// UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostWithBodyWithResponse request with arbitrary body returning *UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse
func (c *ClientWithResponses) UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostWithBodyWithResponse(ctx context.Context, orgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse, error) {
	rsp, err := c.UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse(rsp)
}

func (c *ClientWithResponses) UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostWithResponse(ctx context.Context, orgId string, body UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostJSONRequestBody, reqEditors ...RequestEditorFn) (*UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse, error) {
	rsp, err := c.UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePost(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse(rsp)
}

// UobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteWithResponse request returning *UobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteResponse
func (c *ClientWithResponses) UobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteWithResponse(ctx context.Context, orgId string, connectorId string, reqEditors ...RequestEditorFn) (*UobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteResponse, error) {
	rsp, err := c.UobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDelete(ctx, orgId, connectorId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteResponse(rsp)
}

// UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutWithBodyWithResponse request with arbitrary body returning *UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse
func (c *ClientWithResponses) UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutWithBodyWithResponse(ctx context.Context, orgId string, connectorId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse, error) {
	rsp, err := c.UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutWithBody(ctx, orgId, connectorId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse(rsp)
}

func (c *ClientWithResponses) UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutWithResponse(ctx context.Context, orgId string, connectorId string, body UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutJSONRequestBody, reqEditors ...RequestEditorFn) (*UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse, error) {
	rsp, err := c.UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPut(ctx, orgId, connectorId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse(rsp)
}

// UobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostWithResponse request returning *UobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostResponse
func (c *ClientWithResponses) UobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostWithResponse(ctx context.Context, orgId string, connectorId string, reqEditors ...RequestEditorFn) (*UobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostResponse, error) {
	rsp, err := c.UobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPost(ctx, orgId, connectorId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostResponse(rsp)
}

// ParseUobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetResponse parses an HTTP response from a UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetWithResponse call
func ParseUobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetResponse(rsp *http.Response) (*UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetResponse parses an HTTP response from a UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetWithResponse call
func ParseUobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetResponse(rsp *http.Response) (*UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetResponse parses an HTTP response from a UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetWithResponse call
func ParseUobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetResponse(rsp *http.Response) (*UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetResponse parses an HTTP response from a UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetWithResponse call
func ParseUobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetResponse(rsp *http.Response) (*UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteResponse parses an HTTP response from a UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteWithResponse call
func ParseUobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteResponse(rsp *http.Response) (*UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsTriggerOnboardingDeleteUobsV1OrgsOrgIdCloudOnboardingDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse parses an HTTP response from a UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostWithResponse call
func ParseUobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse(rsp *http.Response) (*UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsTriggerOnboardingPostGcpUobsV1OrgsOrgIdCloudOnboardingGcpPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse parses an HTTP response from a UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutWithResponse call
func ParseUobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse(rsp *http.Response) (*UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsTriggerOnboardingPutGcpUobsV1OrgsOrgIdCloudOnboardingGcpConnectorIdPutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetResponse parses an HTTP response from a UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetWithResponse call
func ParseUobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetResponse(rsp *http.Response) (*UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsListConnectorsUobsV1OrgsOrgIdSaasConnectorsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UobsOkResponseSaasConnectorRead
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetResponse parses an HTTP response from a UobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetWithResponse call
func ParseUobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetResponse(rsp *http.Response) (*UobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsGetConnectorsCountUobsV1OrgsOrgIdSaasConnectorsCountGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetResponse parses an HTTP response from a UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetWithResponse call
func ParseUobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetResponse(rsp *http.Response) (*UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsGetConnectorStatusUobsV1OrgsOrgIdSaasConnectorsStatusGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetResponse parses an HTTP response from a UobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetWithResponse call
func ParseUobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetResponse(rsp *http.Response) (*UobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsGetConnectorUobsV1OrgsOrgIdSaasConnectorsIdentifierGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UobsOkResponseSaasConnectorRead
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse parses an HTTP response from a UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostWithResponse call
func ParseUobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse(rsp *http.Response) (*UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsCreateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse parses an HTTP response from a UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostWithResponse call
func ParseUobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse(rsp *http.Response) (*UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsValidateSaasConnectionUobsV1OrgsOrgIdSaasOnboardingValidatePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UobsOkResponseValidationResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteResponse parses an HTTP response from a UobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteWithResponse call
func ParseUobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteResponse(rsp *http.Response) (*UobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsDeleteSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse parses an HTTP response from a UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutWithResponse call
func ParseUobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse(rsp *http.Response) (*UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsUpdateSaasOnboardingUobsV1OrgsOrgIdSaasOnboardingConnectorIdPutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseUobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostResponse parses an HTTP response from a UobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostWithResponse call
func ParseUobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostResponse(rsp *http.Response) (*UobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UobsCollectSaasConnectorUobsV1OrgsOrgIdSaasOnboardingConnectorIdCollectPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest UobsOkResponseAny
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UobsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}
