// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 and cmd/split-client. DO NOT EDIT.

package flexera

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	"io"
	"net/http"
	"net/url"
)

// Defines values for FinopsCustomizationsCreateRequestBodyDashboardScope.
const (
	FinopsCustomizationsCreateRequestBodyDashboardScopeOrg  FinopsCustomizationsCreateRequestBodyDashboardScope = "org"
	FinopsCustomizationsCreateRequestBodyDashboardScopeUser FinopsCustomizationsCreateRequestBodyDashboardScope = "user"
)

// Defines values for FinopsCustomizationsCreateRequestBodyVisibility.
const (
	FinopsCustomizationsCreateRequestBodyVisibilityPrivate FinopsCustomizationsCreateRequestBodyVisibility = "private"
	FinopsCustomizationsCreateRequestBodyVisibilityShared  FinopsCustomizationsCreateRequestBodyVisibility = "shared"
)

// Defines values for FinopsCustomizationsCreateRequestBody2Visibility.
const (
	FinopsCustomizationsCreateRequestBody2VisibilityPrivate FinopsCustomizationsCreateRequestBody2Visibility = "private"
	FinopsCustomizationsCreateRequestBody2VisibilityShared  FinopsCustomizationsCreateRequestBody2Visibility = "shared"
)

// Defines values for FinopsCustomizationsUpdateRequestBodyVisibility.
const (
	FinopsCustomizationsUpdateRequestBodyVisibilityPrivate FinopsCustomizationsUpdateRequestBodyVisibility = "private"
	FinopsCustomizationsUpdateRequestBodyVisibilityShared  FinopsCustomizationsUpdateRequestBodyVisibility = "shared"
)

// Defines values for FinopsCustomizationsUpdateRequestBody2Visibility.
const (
	FinopsCustomizationsUpdateRequestBody2VisibilityPrivate FinopsCustomizationsUpdateRequestBody2Visibility = "private"
	FinopsCustomizationsUpdateRequestBody2VisibilityShared  FinopsCustomizationsUpdateRequestBody2Visibility = "shared"
)

// FinopsCustomizationsCreateRequestBody defines model for FinopsCustomizations_CreateRequestBody.
type FinopsCustomizationsCreateRequestBody struct {
	// DashboardId Identifier of the dashboard to render and send.
	DashboardId string `json:"dashboardId"`

	// DashboardScope Which dashboard store resolves the target dashboard.
	DashboardScope FinopsCustomizationsCreateRequestBodyDashboardScope `json:"dashboardScope"`

	// Enabled Whether the schedule is active.
	Enabled *bool `json:"enabled,omitempty"`

	// Name Human-readable name for the subscription
	Name string `json:"name"`

	// Recipients Delivery targets (at least one).
	Recipients []FinopsCustomizationsReportSubscriptionRecipient `json:"recipients"`

	// Schedule When a scheduled report fires.
	Schedule FinopsCustomizationsReportSubscriptionSchedule `json:"schedule"`

	// Visibility Visibility scope.
	Visibility *FinopsCustomizationsCreateRequestBodyVisibility `json:"visibility,omitempty"`
}

// FinopsCustomizationsCreateRequestBodyDashboardScope Which dashboard store resolves the target dashboard.
type FinopsCustomizationsCreateRequestBodyDashboardScope string

// FinopsCustomizationsCreateRequestBodyVisibility Visibility scope.
type FinopsCustomizationsCreateRequestBodyVisibility string

// FinopsCustomizationsCreateRequestBody2 defines model for FinopsCustomizations_CreateRequestBody2.
type FinopsCustomizationsCreateRequestBody2 struct {
	// Description Optional description
	Description *string `json:"description,omitempty"`

	// Dimensions Optional list of dimensions for GROUP BY (max 10).
	Dimensions *[]string `json:"dimensions,omitempty"`

	// Filter A single filter node: a leaf test (equal, substring) or a boolean combinator (and, or, not).
	Filter *FinopsCustomizationsFilterV1 `json:"filter,omitempty"`

	// Name Human-readable name for the filter
	Name string `json:"name"`

	// Visibility Filter visibility scope
	Visibility FinopsCustomizationsCreateRequestBody2Visibility `json:"visibility"`
}

// FinopsCustomizationsCreateRequestBody2Visibility Filter visibility scope
type FinopsCustomizationsCreateRequestBody2Visibility string

// FinopsCustomizationsCreateRequestBody3 defines model for FinopsCustomizations_CreateRequestBody3.
type FinopsCustomizationsCreateRequestBody3 struct {
	// Name Name of the tag dimension to be displayed in the UI.
	Name string `json:"name"`

	// Tags Specifies the resource tag keys used to derive values for this dimension. If a resource has multiple matching tags, the value from the earliest listed tag is used.
	Tags []FinopsCustomizationsTagDimensionTag `json:"tags"`
}

// FinopsCustomizationsRuleBasedDimensionCreateRequestBody defines model for FinopsCustomizations_RuleBasedDimensionCreateRequestBody.
type FinopsCustomizationsRuleBasedDimensionCreateRequestBody struct {
	// Name Display name for the dimension in the UI
	Name string `json:"name"`
}

// FinopsCustomizationsRulesListReplaceRequestBody defines model for FinopsCustomizations_RulesListReplaceRequestBody.
type FinopsCustomizationsRulesListReplaceRequestBody struct {
	// Rules Rules for how the dimension will be populated. A rules list normally supports up to 500 rules. A simple mapping-style list may support up to 40,000 raw rules if it optimizes into no more than 500 rule groups. After mapping optimization, plain rules in one list may contain up to 1,000 condition expression elements. Across all rule-based dimensions, a single effective month may have up to 400,000 applicable raw rules in total, and up to 2,000 optimized rule groups after mapping optimization.
	Rules []FinopsCustomizationsRuleBasedDimensionRulePayload `json:"rules"`
}

// FinopsCustomizationsUpdateRequestBody defines model for FinopsCustomizations_UpdateRequestBody.
type FinopsCustomizationsUpdateRequestBody struct {
	// Enabled Updated active state.
	Enabled *bool `json:"enabled,omitempty"`

	// Name Updated name.
	Name *string `json:"name,omitempty"`

	// Recipients Updated delivery targets (must remain non-empty if provided).
	Recipients *[]FinopsCustomizationsReportSubscriptionRecipient `json:"recipients,omitempty"`

	// Schedule When a scheduled report fires.
	Schedule *FinopsCustomizationsReportSubscriptionSchedule `json:"schedule,omitempty"`

	// Visibility Updated visibility scope.
	Visibility *FinopsCustomizationsUpdateRequestBodyVisibility `json:"visibility,omitempty"`
}

// FinopsCustomizationsUpdateRequestBodyVisibility Updated visibility scope.
type FinopsCustomizationsUpdateRequestBodyVisibility string

// FinopsCustomizationsUpdateRequestBody2 defines model for FinopsCustomizations_UpdateRequestBody2.
type FinopsCustomizationsUpdateRequestBody2 struct {
	// Description Description
	Description string `json:"description"`

	// Dimensions Optional list of dimensions for GROUP BY (max 10).
	Dimensions *[]string `json:"dimensions,omitempty"`

	// Filter A single filter node: a leaf test (equal, substring) or a boolean combinator (and, or, not).
	Filter *FinopsCustomizationsFilterV1 `json:"filter,omitempty"`

	// Name Human-readable name for the filter
	Name string `json:"name"`

	// Visibility Filter visibility scope
	Visibility FinopsCustomizationsUpdateRequestBody2Visibility `json:"visibility"`
}

// FinopsCustomizationsUpdateRequestBody2Visibility Filter visibility scope
type FinopsCustomizationsUpdateRequestBody2Visibility string

// FinopsCustomizationsReportSubscriptionsIndexParams defines parameters for FinopsCustomizationsReportSubscriptionsIndex.
type FinopsCustomizationsReportSubscriptionsIndexParams struct {
	// SkipToken An opaque token to be provided when requesting a subsequent page after receiving a partial response.
	// Partial responses will include a "nextPage" attribute in their response body, which contains the URL of the next page including the appropriate skipToken.
	SkipToken *string `form:"skipToken,omitempty" json:"skipToken,omitempty"`

	// Limit Page size (default 50, max 200)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// DashboardId Optional filter: only subscriptions targeting this dashboard.
	DashboardId *string `form:"dashboardId,omitempty" json:"dashboardId,omitempty"`
}

// FinopsCustomizationsReportSubscriptionsDeleteParams defines parameters for FinopsCustomizationsReportSubscriptionsDelete.
type FinopsCustomizationsReportSubscriptionsDeleteParams struct {
	// IfMatch Only modify the report subscription if this tag is still current.
	IfMatch *string `json:"If-Match,omitempty"`
}

// FinopsCustomizationsReportSubscriptionsUpdateParams defines parameters for FinopsCustomizationsReportSubscriptionsUpdate.
type FinopsCustomizationsReportSubscriptionsUpdateParams struct {
	// IfMatch Only modify the report subscription if this tag is still current.
	IfMatch *string `json:"If-Match,omitempty"`
}

// FinopsCustomizationsSavedFiltersIndexParams defines parameters for FinopsCustomizationsSavedFiltersIndex.
type FinopsCustomizationsSavedFiltersIndexParams struct {
	// SkipToken An opaque token to be provided when requesting a subsequent page after receiving a partial response.
	// Partial responses will include a "nextPage" attribute in their response body, which contains the URL of the next page including the appropriate skipToken.
	SkipToken *string `form:"skipToken,omitempty" json:"skipToken,omitempty"`

	// Limit Page size (default 10, max 200)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// OrderBy Optional orderBy query allows to specify an expression for determining what values are used to order the entities.
	//             Multiple expressions can be specified using comma separated values.
	OrderBy *string `form:"orderBy,omitempty" json:"orderBy,omitempty"`

	// Visibility Optional visibility filter for results.
	Visibility *FinopsCustomizationsSavedFiltersIndexParamsVisibility `form:"visibility,omitempty" json:"visibility,omitempty"`

	// FavoriteIds Comma-separated saved filter IDs marked as favorites, max 50.
	FavoriteIds *string `form:"favoriteIds,omitempty" json:"favoriteIds,omitempty"`
}

// FinopsCustomizationsSavedFiltersShowParams defines parameters for FinopsCustomizationsSavedFiltersShow.
type FinopsCustomizationsSavedFiltersShowParams struct {
	// IfNoneMatch Only return the saved filter if its ETag differs from this value; otherwise respond 304 Not Modified.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// FinopsCustomizationsSavedFiltersPatchParams defines parameters for FinopsCustomizationsSavedFiltersPatch.
type FinopsCustomizationsSavedFiltersPatchParams struct {
	// IfMatch Only modify the saved filter if this tag is still current.
	IfMatch *string `json:"If-Match,omitempty"`
}

// FinopsCustomizationsSavedFiltersUpdateParams defines parameters for FinopsCustomizationsSavedFiltersUpdate.
type FinopsCustomizationsSavedFiltersUpdateParams struct {
	// IfMatch Only modify the saved filter if this tag is still current.
	IfMatch *string `json:"If-Match,omitempty"`
}

// FinopsCustomizationsReportSubscriptionsCreateJSONRequestBody defines body for FinopsCustomizationsReportSubscriptionsCreate for application/json ContentType.
type FinopsCustomizationsReportSubscriptionsCreateJSONRequestBody = FinopsCustomizationsCreateRequestBody

// FinopsCustomizationsReportSubscriptionsUpdateJSONRequestBody defines body for FinopsCustomizationsReportSubscriptionsUpdate for application/json ContentType.
type FinopsCustomizationsReportSubscriptionsUpdateJSONRequestBody = FinopsCustomizationsUpdateRequestBody

// FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateJSONRequestBody defines body for FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdate for application/json ContentType.
type FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateJSONRequestBody = FinopsCustomizationsRuleBasedDimensionCreateRequestBody

// FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateJSONRequestBody defines body for FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreate for application/json ContentType.
type FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateJSONRequestBody = FinopsCustomizationsRuleBasedDimensionCreateRequestBody

// FinopsCustomizationsRuleBasedDimensionRulesListReplaceJSONRequestBody defines body for FinopsCustomizationsRuleBasedDimensionRulesListReplace for application/json ContentType.
type FinopsCustomizationsRuleBasedDimensionRulesListReplaceJSONRequestBody = FinopsCustomizationsRulesListReplaceRequestBody

// FinopsCustomizationsSavedFiltersCreateJSONRequestBody defines body for FinopsCustomizationsSavedFiltersCreate for application/json ContentType.
type FinopsCustomizationsSavedFiltersCreateJSONRequestBody = FinopsCustomizationsCreateRequestBody2

// FinopsCustomizationsSavedFiltersPatchJSONRequestBody defines body for FinopsCustomizationsSavedFiltersPatch for application/json ContentType.
type FinopsCustomizationsSavedFiltersPatchJSONRequestBody = FinopsCustomizationsPatchSavedFilterRequest

// FinopsCustomizationsSavedFiltersUpdateJSONRequestBody defines body for FinopsCustomizationsSavedFiltersUpdate for application/json ContentType.
type FinopsCustomizationsSavedFiltersUpdateJSONRequestBody = FinopsCustomizationsUpdateRequestBody2

// FinopsCustomizationsTagDimensionCreateJSONRequestBody defines body for FinopsCustomizationsTagDimensionCreate for application/json ContentType.
type FinopsCustomizationsTagDimensionCreateJSONRequestBody = FinopsCustomizationsCreateRequestBody3

// FinopsCustomizationsTagDimensionUpdateJSONRequestBody defines body for FinopsCustomizationsTagDimensionUpdate for application/json ContentType.
type FinopsCustomizationsTagDimensionUpdateJSONRequestBody = FinopsCustomizationsCreateRequestBody3

func (c *Client) FinopsCustomizationsReportSubscriptionsIndex(ctx context.Context, orgId int, params *FinopsCustomizationsReportSubscriptionsIndexParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsReportSubscriptionsIndexRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsReportSubscriptionsCreateWithBody(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsReportSubscriptionsCreateRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsReportSubscriptionsCreate(ctx context.Context, orgId int, body FinopsCustomizationsReportSubscriptionsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsReportSubscriptionsCreateRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsReportSubscriptionsDelete(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsReportSubscriptionsDeleteParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsReportSubscriptionsDeleteRequest(c.Server, orgId, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsReportSubscriptionsShow(ctx context.Context, orgId int, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsReportSubscriptionsShowRequest(c.Server, orgId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsReportSubscriptionsUpdateWithBody(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsReportSubscriptionsUpdateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsReportSubscriptionsUpdateRequestWithBody(c.Server, orgId, id, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsReportSubscriptionsUpdate(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsReportSubscriptionsUpdateParams, body FinopsCustomizationsReportSubscriptionsUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsReportSubscriptionsUpdateRequest(c.Server, orgId, id, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionIndex(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionIndexRequest(c.Server, orgId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDelete(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteRequest(c.Server, orgId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShow(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowRequest(c.Server, orgId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateWithBody(ctx context.Context, orgId int, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateRequestWithBody(c.Server, orgId, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdate(ctx context.Context, orgId int, id string, body FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateRequest(c.Server, orgId, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateWithBody(ctx context.Context, orgId int, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateRequestWithBody(c.Server, orgId, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreate(ctx context.Context, orgId int, id string, body FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateRequest(c.Server, orgId, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionRulesListDelete(ctx context.Context, orgId int, id string, effectiveAt string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionRulesListDeleteRequest(c.Server, orgId, id, effectiveAt)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionRulesListShow(ctx context.Context, orgId int, id string, effectiveAt string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionRulesListShowRequest(c.Server, orgId, id, effectiveAt)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionRulesListReplaceWithBody(ctx context.Context, orgId int, id string, effectiveAt string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionRulesListReplaceRequestWithBody(c.Server, orgId, id, effectiveAt, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionRulesListReplace(ctx context.Context, orgId int, id string, effectiveAt string, body FinopsCustomizationsRuleBasedDimensionRulesListReplaceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionRulesListReplaceRequest(c.Server, orgId, id, effectiveAt, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShow(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowRequest(c.Server, orgId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsSavedFiltersIndex(ctx context.Context, orgId int, params *FinopsCustomizationsSavedFiltersIndexParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsSavedFiltersIndexRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsSavedFiltersCreateWithBody(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsSavedFiltersCreateRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsSavedFiltersCreate(ctx context.Context, orgId int, body FinopsCustomizationsSavedFiltersCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsSavedFiltersCreateRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsSavedFiltersDelete(ctx context.Context, orgId int, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsSavedFiltersDeleteRequest(c.Server, orgId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsSavedFiltersShow(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersShowParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsSavedFiltersShowRequest(c.Server, orgId, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsSavedFiltersPatchWithBody(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersPatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsSavedFiltersPatchRequestWithBody(c.Server, orgId, id, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsSavedFiltersPatch(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersPatchParams, body FinopsCustomizationsSavedFiltersPatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsSavedFiltersPatchRequest(c.Server, orgId, id, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsSavedFiltersUpdateWithBody(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersUpdateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsSavedFiltersUpdateRequestWithBody(c.Server, orgId, id, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsSavedFiltersUpdate(ctx context.Context, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersUpdateParams, body FinopsCustomizationsSavedFiltersUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsSavedFiltersUpdateRequest(c.Server, orgId, id, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsTagDimensionIndex(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsTagDimensionIndexRequest(c.Server, orgId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsTagDimensionCreateWithBody(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsTagDimensionCreateRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsTagDimensionCreate(ctx context.Context, orgId int, body FinopsCustomizationsTagDimensionCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsTagDimensionCreateRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsTagDimensionDelete(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsTagDimensionDeleteRequest(c.Server, orgId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsTagDimensionShow(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsTagDimensionShowRequest(c.Server, orgId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsTagDimensionUpdateWithBody(ctx context.Context, orgId int, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsTagDimensionUpdateRequestWithBody(c.Server, orgId, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinopsCustomizationsTagDimensionUpdate(ctx context.Context, orgId int, id string, body FinopsCustomizationsTagDimensionUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinopsCustomizationsTagDimensionUpdateRequest(c.Server, orgId, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewFinopsCustomizationsReportSubscriptionsIndexRequest generates requests for FinopsCustomizationsReportSubscriptionsIndex
func NewFinopsCustomizationsReportSubscriptionsIndexRequest(server string, orgId int, params *FinopsCustomizationsReportSubscriptionsIndexParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/report-subscriptions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.SkipToken != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "skipToken", runtime.ParamLocationQuery, *params.SkipToken); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DashboardId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "dashboardId", runtime.ParamLocationQuery, *params.DashboardId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsReportSubscriptionsCreateRequest calls the generic FinopsCustomizationsReportSubscriptionsCreate builder with application/json body
func NewFinopsCustomizationsReportSubscriptionsCreateRequest(server string, orgId int, body FinopsCustomizationsReportSubscriptionsCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFinopsCustomizationsReportSubscriptionsCreateRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewFinopsCustomizationsReportSubscriptionsCreateRequestWithBody generates requests for FinopsCustomizationsReportSubscriptionsCreate with any type of body
func NewFinopsCustomizationsReportSubscriptionsCreateRequestWithBody(server string, orgId int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/report-subscriptions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewFinopsCustomizationsReportSubscriptionsDeleteRequest generates requests for FinopsCustomizationsReportSubscriptionsDelete
func NewFinopsCustomizationsReportSubscriptionsDeleteRequest(server string, orgId int, id openapi_types.UUID, params *FinopsCustomizationsReportSubscriptionsDeleteParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/report-subscriptions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IfMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "If-Match", runtime.ParamLocationHeader, *params.IfMatch)
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-Match", headerParam0)
		}

	}

	return req, nil
}

// NewFinopsCustomizationsReportSubscriptionsShowRequest generates requests for FinopsCustomizationsReportSubscriptionsShow
func NewFinopsCustomizationsReportSubscriptionsShowRequest(server string, orgId int, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/report-subscriptions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsReportSubscriptionsUpdateRequest calls the generic FinopsCustomizationsReportSubscriptionsUpdate builder with application/json body
func NewFinopsCustomizationsReportSubscriptionsUpdateRequest(server string, orgId int, id openapi_types.UUID, params *FinopsCustomizationsReportSubscriptionsUpdateParams, body FinopsCustomizationsReportSubscriptionsUpdateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFinopsCustomizationsReportSubscriptionsUpdateRequestWithBody(server, orgId, id, params, "application/json", bodyReader)
}

// NewFinopsCustomizationsReportSubscriptionsUpdateRequestWithBody generates requests for FinopsCustomizationsReportSubscriptionsUpdate with any type of body
func NewFinopsCustomizationsReportSubscriptionsUpdateRequestWithBody(server string, orgId int, id openapi_types.UUID, params *FinopsCustomizationsReportSubscriptionsUpdateParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/report-subscriptions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.IfMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "If-Match", runtime.ParamLocationHeader, *params.IfMatch)
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-Match", headerParam0)
		}

	}

	return req, nil
}

// NewFinopsCustomizationsRuleBasedDimensionIndexRequest generates requests for FinopsCustomizationsRuleBasedDimensionIndex
func NewFinopsCustomizationsRuleBasedDimensionIndexRequest(server string, orgId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/rule-based-dimensions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteRequest generates requests for FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDelete
func NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionDeleteRequest(server string, orgId int, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/rule-based-dimensions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowRequest generates requests for FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShow
func NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionShowRequest(server string, orgId int, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/rule-based-dimensions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateRequest calls the generic FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdate builder with application/json body
func NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateRequest(server string, orgId int, id string, body FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateRequestWithBody(server, orgId, id, "application/json", bodyReader)
}

// NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateRequestWithBody generates requests for FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdate with any type of body
func NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionUpdateRequestWithBody(server string, orgId int, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/rule-based-dimensions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateRequest calls the generic FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreate builder with application/json body
func NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateRequest(server string, orgId int, id string, body FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateRequestWithBody(server, orgId, id, "application/json", bodyReader)
}

// NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateRequestWithBody generates requests for FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreate with any type of body
func NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionCreateRequestWithBody(server string, orgId int, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/rule-based-dimensions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewFinopsCustomizationsRuleBasedDimensionRulesListDeleteRequest generates requests for FinopsCustomizationsRuleBasedDimensionRulesListDelete
func NewFinopsCustomizationsRuleBasedDimensionRulesListDeleteRequest(server string, orgId int, id string, effectiveAt string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "effectiveAt", runtime.ParamLocationPath, effectiveAt)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/rule-based-dimensions/%s/rules/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsRuleBasedDimensionRulesListShowRequest generates requests for FinopsCustomizationsRuleBasedDimensionRulesListShow
func NewFinopsCustomizationsRuleBasedDimensionRulesListShowRequest(server string, orgId int, id string, effectiveAt string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "effectiveAt", runtime.ParamLocationPath, effectiveAt)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/rule-based-dimensions/%s/rules/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsRuleBasedDimensionRulesListReplaceRequest calls the generic FinopsCustomizationsRuleBasedDimensionRulesListReplace builder with application/json body
func NewFinopsCustomizationsRuleBasedDimensionRulesListReplaceRequest(server string, orgId int, id string, effectiveAt string, body FinopsCustomizationsRuleBasedDimensionRulesListReplaceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFinopsCustomizationsRuleBasedDimensionRulesListReplaceRequestWithBody(server, orgId, id, effectiveAt, "application/json", bodyReader)
}

// NewFinopsCustomizationsRuleBasedDimensionRulesListReplaceRequestWithBody generates requests for FinopsCustomizationsRuleBasedDimensionRulesListReplace with any type of body
func NewFinopsCustomizationsRuleBasedDimensionRulesListReplaceRequestWithBody(server string, orgId int, id string, effectiveAt string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "effectiveAt", runtime.ParamLocationPath, effectiveAt)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/rule-based-dimensions/%s/rules/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowRequest generates requests for FinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShow
func NewFinopsCustomizationsRuleBasedDimensionRuleBasedDimensionSummaryShowRequest(server string, orgId int, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/rule-based-dimensions/%s/summary", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsSavedFiltersIndexRequest generates requests for FinopsCustomizationsSavedFiltersIndex
func NewFinopsCustomizationsSavedFiltersIndexRequest(server string, orgId int, params *FinopsCustomizationsSavedFiltersIndexParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/saved-filters", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.SkipToken != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "skipToken", runtime.ParamLocationQuery, *params.SkipToken); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrderBy != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "orderBy", runtime.ParamLocationQuery, *params.OrderBy); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Visibility != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "visibility", runtime.ParamLocationQuery, *params.Visibility); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FavoriteIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "favoriteIds", runtime.ParamLocationQuery, *params.FavoriteIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsSavedFiltersCreateRequest calls the generic FinopsCustomizationsSavedFiltersCreate builder with application/json body
func NewFinopsCustomizationsSavedFiltersCreateRequest(server string, orgId int, body FinopsCustomizationsSavedFiltersCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFinopsCustomizationsSavedFiltersCreateRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewFinopsCustomizationsSavedFiltersCreateRequestWithBody generates requests for FinopsCustomizationsSavedFiltersCreate with any type of body
func NewFinopsCustomizationsSavedFiltersCreateRequestWithBody(server string, orgId int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/saved-filters", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewFinopsCustomizationsSavedFiltersDeleteRequest generates requests for FinopsCustomizationsSavedFiltersDelete
func NewFinopsCustomizationsSavedFiltersDeleteRequest(server string, orgId int, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/saved-filters/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsSavedFiltersShowRequest generates requests for FinopsCustomizationsSavedFiltersShow
func NewFinopsCustomizationsSavedFiltersShowRequest(server string, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersShowParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/saved-filters/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IfNoneMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "If-None-Match", runtime.ParamLocationHeader, *params.IfNoneMatch)
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-None-Match", headerParam0)
		}

	}

	return req, nil
}

// NewFinopsCustomizationsSavedFiltersPatchRequest calls the generic FinopsCustomizationsSavedFiltersPatch builder with application/json body
func NewFinopsCustomizationsSavedFiltersPatchRequest(server string, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersPatchParams, body FinopsCustomizationsSavedFiltersPatchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFinopsCustomizationsSavedFiltersPatchRequestWithBody(server, orgId, id, params, "application/json", bodyReader)
}

// NewFinopsCustomizationsSavedFiltersPatchRequestWithBody generates requests for FinopsCustomizationsSavedFiltersPatch with any type of body
func NewFinopsCustomizationsSavedFiltersPatchRequestWithBody(server string, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersPatchParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/saved-filters/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.IfMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "If-Match", runtime.ParamLocationHeader, *params.IfMatch)
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-Match", headerParam0)
		}

	}

	return req, nil
}

// NewFinopsCustomizationsSavedFiltersUpdateRequest calls the generic FinopsCustomizationsSavedFiltersUpdate builder with application/json body
func NewFinopsCustomizationsSavedFiltersUpdateRequest(server string, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersUpdateParams, body FinopsCustomizationsSavedFiltersUpdateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFinopsCustomizationsSavedFiltersUpdateRequestWithBody(server, orgId, id, params, "application/json", bodyReader)
}

// NewFinopsCustomizationsSavedFiltersUpdateRequestWithBody generates requests for FinopsCustomizationsSavedFiltersUpdate with any type of body
func NewFinopsCustomizationsSavedFiltersUpdateRequestWithBody(server string, orgId int, id openapi_types.UUID, params *FinopsCustomizationsSavedFiltersUpdateParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/saved-filters/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.IfMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "If-Match", runtime.ParamLocationHeader, *params.IfMatch)
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-Match", headerParam0)
		}

	}

	return req, nil
}

// NewFinopsCustomizationsTagDimensionIndexRequest generates requests for FinopsCustomizationsTagDimensionIndex
func NewFinopsCustomizationsTagDimensionIndexRequest(server string, orgId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/tag-dimensions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsTagDimensionCreateRequest calls the generic FinopsCustomizationsTagDimensionCreate builder with application/json body
func NewFinopsCustomizationsTagDimensionCreateRequest(server string, orgId int, body FinopsCustomizationsTagDimensionCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFinopsCustomizationsTagDimensionCreateRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewFinopsCustomizationsTagDimensionCreateRequestWithBody generates requests for FinopsCustomizationsTagDimensionCreate with any type of body
func NewFinopsCustomizationsTagDimensionCreateRequestWithBody(server string, orgId int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/tag-dimensions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewFinopsCustomizationsTagDimensionDeleteRequest generates requests for FinopsCustomizationsTagDimensionDelete
func NewFinopsCustomizationsTagDimensionDeleteRequest(server string, orgId int, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/tag-dimensions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsTagDimensionShowRequest generates requests for FinopsCustomizationsTagDimensionShow
func NewFinopsCustomizationsTagDimensionShowRequest(server string, orgId int, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/tag-dimensions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinopsCustomizationsTagDimensionUpdateRequest calls the generic FinopsCustomizationsTagDimensionUpdate builder with application/json body
func NewFinopsCustomizationsTagDimensionUpdateRequest(server string, orgId int, id string, body FinopsCustomizationsTagDimensionUpdateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFinopsCustomizationsTagDimensionUpdateRequestWithBody(server, orgId, id, "application/json", bodyReader)
}

// NewFinopsCustomizationsTagDimensionUpdateRequestWithBody generates requests for FinopsCustomizationsTagDimensionUpdate with any type of body
func NewFinopsCustomizationsTagDimensionUpdateRequestWithBody(server string, orgId int, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-customizations/v1/orgs/%s/tag-dimensions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}
