// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 and cmd/split-client. DO NOT EDIT.

package flexera

import (
	"time"
)

// GrsOrg Flexera One organization resource (subset returned by GRS user-org index).
type GrsOrg struct {
	// Href Canonical GRS href for the organization (e.g. `/grs/orgs/{orgId}`).
	Href *string `json:"href,omitempty"`

	// Id Organization ID.
	Id int64 `json:"id"`

	// Kind Resource kind, typically `org`.
	Kind *string `json:"kind,omitempty"`

	// Name Organization name.
	Name string `json:"name"`
}

// GrsProject Flexera One project resource (subset).
type GrsProject struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Description Project description.
	Description *string `json:"description,omitempty"`

	// Id Project ID.
	Id int64 `json:"id"`

	// Name Project name.
	Name string `json:"name"`

	// OrgId Organization ID the project belongs to.
	OrgId     *int64     `json:"orgId,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}
