# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
output: .client_gen.tmp.go
package: flexera
generate:
  models: true
  client: true
  server-urls: true
