// Package budget provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package budget

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	JWTAuth_header_AuthorizationScopes = "JWTAuth_header_Authorization.Scopes"
)

// ServerUrlTheFlexeraAsiaPacificServer defines the Server URL for The Flexera Asia Pacific server
const ServerUrlTheFlexeraAsiaPacificServer = "https://api.flexera.au"

// ServerUrlTheFlexeraEuropeanServer defines the Server URL for The Flexera European server
const ServerUrlTheFlexeraEuropeanServer = "https://api.flexera.eu"

// ServerUrlTheFlexeraNorthAmericanServer defines the Server URL for The Flexera North American server
const ServerUrlTheFlexeraNorthAmericanServer = "https://api.flexera.com"

// Defines values for BudgetKind.
const (
	FinopsBudget BudgetKind = "finops:budget"
)

// Defines values for BudgetMetric.
const (
	BudgetMetricCostAmortizedBlendedAdj      BudgetMetric = "cost_amortized_blended_adj"
	BudgetMetricCostAmortizedUnblendedAdj    BudgetMetric = "cost_amortized_unblended_adj"
	BudgetMetricCostNonamortizedBlendedAdj   BudgetMetric = "cost_nonamortized_blended_adj"
	BudgetMetricCostNonamortizedUnblendedAdj BudgetMetric = "cost_nonamortized_unblended_adj"
)

// Defines values for BudgetFilterType.
const (
	And   BudgetFilterType = "and"
	Equal BudgetFilterType = "equal"
	Not   BudgetFilterType = "not"
	Or    BudgetFilterType = "or"
)

// Defines values for BudgetLinkKind.
const (
	FinopsBudgetLink BudgetLinkKind = "finops:budget-link"
)

// Defines values for BudgetLinkMetric.
const (
	BudgetLinkMetricCostAmortizedBlendedAdj      BudgetLinkMetric = "cost_amortized_blended_adj"
	BudgetLinkMetricCostAmortizedUnblendedAdj    BudgetLinkMetric = "cost_amortized_unblended_adj"
	BudgetLinkMetricCostNonamortizedBlendedAdj   BudgetLinkMetric = "cost_nonamortized_blended_adj"
	BudgetLinkMetricCostNonamortizedUnblendedAdj BudgetLinkMetric = "cost_nonamortized_unblended_adj"
)

// Defines values for BudgetListKind.
const (
	FinopsBudgetList BudgetListKind = "finops:budget-list"
)

// Defines values for BudgetReportRowKind.
const (
	FinopsBudgetReportRow BudgetReportRowKind = "finops:budget-report-row"
)

// Defines values for BudgetReportRowListKind.
const (
	FinopsBudgetReportRowList BudgetReportRowListKind = "finops:budget-report-row-list"
)

// Defines values for CloudVendorAccountsListKind.
const (
	FinopsCloudVendorAccountList CloudVendorAccountsListKind = "finops:cloud-vendor-account-list"
)

// Defines values for CreateRequestBodyMetric.
const (
	CostAmortizedBlendedAdj      CreateRequestBodyMetric = "cost_amortized_blended_adj"
	CostAmortizedUnblendedAdj    CreateRequestBodyMetric = "cost_amortized_unblended_adj"
	CostNonamortizedBlendedAdj   CreateRequestBodyMetric = "cost_nonamortized_blended_adj"
	CostNonamortizedUnblendedAdj CreateRequestBodyMetric = "cost_nonamortized_unblended_adj"
)

// Defines values for FlexeraFinopsAnalyticsCloudVendorAccountKind.
const (
	FinopsCloudVendorAccountAws FlexeraFinopsAnalyticsCloudVendorAccountKind = "finops:cloud-vendor-account-aws"
)

// Defines values for FlexeraIamPrincipalKind.
const (
	IamServiceAccount FlexeraIamPrincipalKind = "iam:service-account"
	IamUser           FlexeraIamPrincipalKind = "iam:user"
)

// AccountDetailsAws AWS account details.
type AccountDetailsAws struct {
	// AccountId AWS Account ID
	AccountId string `json:"accountId"`

	// Email The email address associated with the AWS account.
	Email string `json:"email"`

	// PayerAccountId AWS Payer Account ID
	PayerAccountId string `json:"payerAccountId"`

	// Status The status of the account. Possible values include `ACTIVE`, `SUSPENDED`, `INOPERABLE`.
	Status string `json:"status"`
}

// Budget defines model for Budget.
type Budget struct {
	// CreatedAt Timestamp representing when the budget was first created
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy A principal is an entity which may perform actions in Flexera One. Users and service accounts are examples of principals.
	CreatedBy *FlexeraIamPrincipal `json:"createdBy,omitempty"`

	// Dimensions Dimensions used to break down this budget. Each budget segment will be defined as a unique combination of these dimension values.
	Dimensions []string `json:"dimensions"`

	// Filter A filter expression defines the scope of the budget, in terms of specific dimension values. This is useful when generating a budget report, as it allows you to exclude certain line items from the report, rather than have them reported as 'unbudgeted'. For example, you might define the budget filter to only include AWS costs, and exclude all Tax line items from the budget.
	//
	// The filter behaves similar to a WHERE clause in SQL, describing which rows should be included in the budget.
	// An empty filter expression implies all costs are included.
	//
	// To define a filter, the 'type' field is required, and then other field(s) will be required depending on that selected type.
	// The primary filter type is 'equal', checking the value of one dimension. And then the other types, 'and', 'or', and 'not', are used to build more complex expressions.
	//
	// Examples of each filter type:
	// ```
	// {"type":"equal", "dimension":"vendor", "value":"AWS"}
	//
	// {"type":"and", "expressions":[
	//   {"type":"equal", "dimension":"vendor", "value":"AWS"},
	//   {"type":"equal", "dimension":"rbd_team", "value":"Blue"}
	// ]}
	//
	// {"type":"or", "expressions":[
	//   {"type":"equal", "dimension":"rbd_team", "value":"Blue"},
	//   {"type":"equal", "dimension":"rbd_team", "value":"Green"}
	// ]}
	//
	// {"type":"not", "expression": {
	//   "type":"equal", "dimension":"vendor", "substring":"AWS"
	// }}
	// ```
	// Note: the docs are not being generated correctly for the 'expression' field. It is used with the 'not' filter type and contains another filter expression to be negated.
	Filter *BudgetFilter `json:"filter,omitempty"`

	// Id ID of the budget
	Id string `json:"id"`

	// Kind The resource's type
	Kind BudgetKind `json:"kind"`

	// Metric The cost metric used for the budget
	Metric BudgetMetric `json:"metric"`

	// Name A descriptive name to uniquely identify the budget
	Name string `json:"name"`

	// Segments An array of budget segments, like rows in a spreadsheet. Each segment describes the budget amounts and forecast amounts for a particular combination of dimension values. A budget can define up to 2,000 segments.
	Segments []BudgetSegment `json:"segments"`

	// UpdatedAt Timestamp representing when the budget was most recently updated
	UpdatedAt time.Time `json:"updatedAt"`

	// UpdatedBy A principal is an entity which may perform actions in Flexera One. Users and service accounts are examples of principals.
	UpdatedBy *FlexeraIamPrincipal `json:"updatedBy,omitempty"`

	// YearMonths An array of year-month strings like `"2023-01"`, defining the period covered by the budget.
	YearMonths []string `json:"yearMonths"`
}

// BudgetKind The resource's type
type BudgetKind string

// BudgetMetric The cost metric used for the budget
type BudgetMetric string

// BudgetFilter A filter expression defines the scope of the budget, in terms of specific dimension values. This is useful when generating a budget report, as it allows you to exclude certain line items from the report, rather than have them reported as 'unbudgeted'. For example, you might define the budget filter to only include AWS costs, and exclude all Tax line items from the budget.
//
// The filter behaves similar to a WHERE clause in SQL, describing which rows should be included in the budget.
// An empty filter expression implies all costs are included.
//
// To define a filter, the 'type' field is required, and then other field(s) will be required depending on that selected type.
// The primary filter type is 'equal', checking the value of one dimension. And then the other types, 'and', 'or', and 'not', are used to build more complex expressions.
//
// Examples of each filter type:
// ```
// {"type":"equal", "dimension":"vendor", "value":"AWS"}
//
// {"type":"and", "expressions":[
//
//	{"type":"equal", "dimension":"vendor", "value":"AWS"},
//	{"type":"equal", "dimension":"rbd_team", "value":"Blue"}
//
// ]}
//
// {"type":"or", "expressions":[
//
//	{"type":"equal", "dimension":"rbd_team", "value":"Blue"},
//	{"type":"equal", "dimension":"rbd_team", "value":"Green"}
//
// ]}
//
//	{"type":"not", "expression": {
//	  "type":"equal", "dimension":"vendor", "substring":"AWS"
//	}}
//
// ```
// Note: the docs are not being generated correctly for the 'expression' field. It is used with the 'not' filter type and contains another filter expression to be negated.
type BudgetFilter struct {
	// Dimension name of a dimension to examine. Required for the 'equal' filter type. Note the `billing_center_id` dimension is not supported at this time.
	Dimension *string `json:"dimension,omitempty"`

	// Expression A filter expression defines the scope of the budget, in terms of specific dimension values. This is useful when generating a budget report, as it allows you to exclude certain line items from the report, rather than have them reported as 'unbudgeted'. For example, you might define the budget filter to only include AWS costs, and exclude all Tax line items from the budget.
	//
	// The filter behaves similar to a WHERE clause in SQL, describing which rows should be included in the budget.
	// An empty filter expression implies all costs are included.
	//
	// To define a filter, the 'type' field is required, and then other field(s) will be required depending on that selected type.
	// The primary filter type is 'equal', checking the value of one dimension. And then the other types, 'and', 'or', and 'not', are used to build more complex expressions.
	//
	// Examples of each filter type:
	// ```
	// {"type":"equal", "dimension":"vendor", "value":"AWS"}
	//
	// {"type":"and", "expressions":[
	//   {"type":"equal", "dimension":"vendor", "value":"AWS"},
	//   {"type":"equal", "dimension":"rbd_team", "value":"Blue"}
	// ]}
	//
	// {"type":"or", "expressions":[
	//   {"type":"equal", "dimension":"rbd_team", "value":"Blue"},
	//   {"type":"equal", "dimension":"rbd_team", "value":"Green"}
	// ]}
	//
	// {"type":"not", "expression": {
	//   "type":"equal", "dimension":"vendor", "substring":"AWS"
	// }}
	// ```
	// Note: the docs are not being generated correctly for the 'expression' field. It is used with the 'not' filter type and contains another filter expression to be negated.
	Expression *BudgetFilter `json:"expression,omitempty"`

	// Expressions the filter expressions that will be AND'd or OR'd together. Required for the 'and' and 'or' filter types.
	Expressions *[]BudgetFilter `json:"expressions,omitempty"`

	// Type This 'type' param is required, but what the other param(s) are required will depend on what type is selected.
	Type BudgetFilterType `json:"type"`

	// Value a value that the dimension must match. Required for the 'equal' filter type.
	Value *string `json:"value,omitempty"`
}

// BudgetFilterType This 'type' param is required, but what the other param(s) are required will depend on what type is selected.
type BudgetFilterType string

// BudgetLink A limited view of the budget, used exclusively in index calls.
type BudgetLink struct {
	// CreatedAt Timestamp representing when the budget was first created
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy A principal is an entity which may perform actions in Flexera One. Users and service accounts are examples of principals.
	CreatedBy *FlexeraIamPrincipal `json:"createdBy,omitempty"`

	// Dimensions Dimensions used to break down this budget. Each budget segment will be defined as a unique combination of these dimension values.
	Dimensions []string `json:"dimensions"`

	// Filter A filter expression defines the scope of the budget, in terms of specific dimension values. This is useful when generating a budget report, as it allows you to exclude certain line items from the report, rather than have them reported as 'unbudgeted'. For example, you might define the budget filter to only include AWS costs, and exclude all Tax line items from the budget.
	//
	// The filter behaves similar to a WHERE clause in SQL, describing which rows should be included in the budget.
	// An empty filter expression implies all costs are included.
	//
	// To define a filter, the 'type' field is required, and then other field(s) will be required depending on that selected type.
	// The primary filter type is 'equal', checking the value of one dimension. And then the other types, 'and', 'or', and 'not', are used to build more complex expressions.
	//
	// Examples of each filter type:
	// ```
	// {"type":"equal", "dimension":"vendor", "value":"AWS"}
	//
	// {"type":"and", "expressions":[
	//   {"type":"equal", "dimension":"vendor", "value":"AWS"},
	//   {"type":"equal", "dimension":"rbd_team", "value":"Blue"}
	// ]}
	//
	// {"type":"or", "expressions":[
	//   {"type":"equal", "dimension":"rbd_team", "value":"Blue"},
	//   {"type":"equal", "dimension":"rbd_team", "value":"Green"}
	// ]}
	//
	// {"type":"not", "expression": {
	//   "type":"equal", "dimension":"vendor", "substring":"AWS"
	// }}
	// ```
	// Note: the docs are not being generated correctly for the 'expression' field. It is used with the 'not' filter type and contains another filter expression to be negated.
	Filter *BudgetFilter `json:"filter,omitempty"`

	// Id ID of the budget
	Id string `json:"id"`

	// Kind The resource's type
	Kind BudgetLinkKind `json:"kind"`

	// Metric The cost metric used for the budget
	Metric BudgetLinkMetric `json:"metric"`

	// Name A descriptive name to uniquely identify the budget
	Name string `json:"name"`

	// UpdatedAt Timestamp representing when the budget was most recently updated
	UpdatedAt time.Time `json:"updatedAt"`

	// UpdatedBy A principal is an entity which may perform actions in Flexera One. Users and service accounts are examples of principals.
	UpdatedBy *FlexeraIamPrincipal `json:"updatedBy,omitempty"`

	// YearMonths An array of year-month strings like `"2023-01"`, defining the period covered by the budget.
	YearMonths []string `json:"yearMonths"`
}

// BudgetLinkKind The resource's type
type BudgetLinkKind string

// BudgetLinkMetric The cost metric used for the budget
type BudgetLinkMetric string

// BudgetList defines model for BudgetList.
type BudgetList struct {
	// Kind The resource's type
	Kind BudgetListKind `json:"kind"`

	// Values A condensed view of the collection of all the budgets defined for the organization
	Values []BudgetLink `json:"values"`
}

// BudgetListKind The resource's type
type BudgetListKind string

// BudgetMetrics defines model for BudgetMetrics.
type BudgetMetrics struct {
	// BudgetAmount The budgeted amount of spend
	BudgetAmount *float64 `json:"budgetAmount,omitempty"`

	// ForecastAmount The forecasted amount of spend
	ForecastAmount *float64 `json:"forecastAmount,omitempty"`

	// SpendAmount The actual amount of spend
	SpendAmount *float64 `json:"spendAmount,omitempty"`

	// SpendMinusForecast The variance describing the difference between actual spend and forecasted amount
	SpendMinusForecast *float64 `json:"spendMinusForecast,omitempty"`
}

// BudgetReportRow defines model for BudgetReportRow.
type BudgetReportRow struct {
	// Dimensions One specific combination of dimension values.
	Dimensions map[string]interface{} `json:"dimensions"`

	// Kind The resource's type
	Kind    BudgetReportRowKind `json:"kind"`
	Metrics BudgetMetrics       `json:"metrics"`

	// Timestamp Timestamp of the data point.
	Timestamp time.Time `json:"timestamp"`
}

// BudgetReportRowKind The resource's type
type BudgetReportRowKind string

// BudgetReportRowList defines model for BudgetReportRowList.
type BudgetReportRowList struct {
	// IsPartial Indicates if the report is not showing all budget segments, i.e the user didn't have access to see all the segments
	IsPartial bool `json:"isPartial"`

	// Kind The resource's type
	Kind BudgetReportRowListKind `json:"kind"`

	// PartialReason The reason for returning a partial report
	PartialReason *string `json:"partialReason,omitempty"`

	// Values List of budget report row.
	Values []BudgetReportRow `json:"values"`
}

// BudgetReportRowListKind The resource's type
type BudgetReportRowListKind string

// BudgetSegment Describes a unique combination of dimension values, and provides a corresponding budget amount for each year-month
type BudgetSegment struct {
	// BudgetAmounts The budgeted amount of spend for each year-month
	BudgetAmounts []float64 `json:"budgetAmounts"`

	// DimensionValues A combination of dimension values, unique to this segment in the budget.
	DimensionValues []string `json:"dimensionValues"`

	// ForecastAmounts The forecasted amount of spend for each year-month
	ForecastAmounts *[]float64 `json:"forecastAmounts,omitempty"`
}

// CloudVendorAccountCollection defines model for CloudVendorAccountCollection.
type CloudVendorAccountCollection = []FlexeraFinopsAnalyticsCloudVendorAccount

// CloudVendorAccountsList defines model for CloudVendorAccountsList.
type CloudVendorAccountsList struct {
	// Kind The resource's type
	Kind   CloudVendorAccountsListKind  `json:"kind"`
	Values CloudVendorAccountCollection `json:"values"`
}

// CloudVendorAccountsListKind The resource's type
type CloudVendorAccountsListKind string

// CreateRequestBody defines model for CreateRequestBody.
type CreateRequestBody struct {
	// Dimensions Dimensions used to break down this budget. Each budget segment will be defined as a unique combination of these dimension values.
	Dimensions []string `json:"dimensions"`

	// Filter A filter expression defines the scope of the budget, in terms of specific dimension values. This is useful when generating a budget report, as it allows you to exclude certain line items from the report, rather than have them reported as 'unbudgeted'. For example, you might define the budget filter to only include AWS costs, and exclude all Tax line items from the budget.
	//
	// The filter behaves similar to a WHERE clause in SQL, describing which rows should be included in the budget.
	// An empty filter expression implies all costs are included.
	//
	// To define a filter, the 'type' field is required, and then other field(s) will be required depending on that selected type.
	// The primary filter type is 'equal', checking the value of one dimension. And then the other types, 'and', 'or', and 'not', are used to build more complex expressions.
	//
	// Examples of each filter type:
	// ```
	// {"type":"equal", "dimension":"vendor", "value":"AWS"}
	//
	// {"type":"and", "expressions":[
	//   {"type":"equal", "dimension":"vendor", "value":"AWS"},
	//   {"type":"equal", "dimension":"rbd_team", "value":"Blue"}
	// ]}
	//
	// {"type":"or", "expressions":[
	//   {"type":"equal", "dimension":"rbd_team", "value":"Blue"},
	//   {"type":"equal", "dimension":"rbd_team", "value":"Green"}
	// ]}
	//
	// {"type":"not", "expression": {
	//   "type":"equal", "dimension":"vendor", "substring":"AWS"
	// }}
	// ```
	// Note: the docs are not being generated correctly for the 'expression' field. It is used with the 'not' filter type and contains another filter expression to be negated.
	Filter *BudgetFilter `json:"filter,omitempty"`

	// Metric The cost metric used for the budget
	Metric CreateRequestBodyMetric `json:"metric"`

	// Name A descriptive name to uniquely identify the budget
	Name string `json:"name"`

	// Segments An array of budget segments, like rows in a spreadsheet. Each segment describes the budget amounts and forecast amounts for a particular combination of dimension values. A budget can define up to 2,000 segments.
	Segments []BudgetSegment `json:"segments"`

	// YearMonths An array of year-month strings like `"2023-01"`, defining the period covered by the budget.
	YearMonths []string `json:"yearMonths"`
}

// CreateRequestBodyMetric The cost metric used for the budget
type CreateRequestBodyMetric string

// Error defines model for Error.
type Error struct {
	// Fault Is the error a server-side fault?
	Fault bool `json:"fault"`

	// Id ID is a unique identifier for this particular occurrence of the problem.
	Id string `json:"id"`

	// Message Message is a human-readable explanation specific to this occurrence of the problem.
	Message string `json:"message"`

	// Name Name is the name of this class of errors.
	Name string `json:"name"`

	// Temporary Is the error temporary?
	Temporary bool `json:"temporary"`

	// Timeout Is the error a timeout?
	Timeout bool `json:"timeout"`
}

// FlexeraFinopsAnalyticsCloudVendorAccount Cloud vendor account and its tags.
type FlexeraFinopsAnalyticsCloudVendorAccount struct {
	// Aws AWS account details.
	Aws *AccountDetailsAws `json:"aws,omitempty"`

	// Kind The resource's type
	Kind FlexeraFinopsAnalyticsCloudVendorAccountKind `json:"kind"`

	// LastDiscoveredAt The timestamp when the account details were last loaded from the cloud vendor.
	LastDiscoveredAt time.Time `json:"lastDiscoveredAt"`

	// Name Name of the account.
	Name string `json:"name"`

	// Tags Tags attached to the account, as key-value pairs.
	Tags map[string]string `json:"tags"`
}

// FlexeraFinopsAnalyticsCloudVendorAccountKind The resource's type
type FlexeraFinopsAnalyticsCloudVendorAccountKind string

// FlexeraIamPrincipal A principal is an entity which may perform actions in Flexera One. Users and service accounts are examples of principals.
type FlexeraIamPrincipal struct {
	// Id The principal's unique identifier (ID)
	Id int `json:"id"`

	// Kind The resource's type
	Kind FlexeraIamPrincipalKind `json:"kind"`

	// Ref A string used to refer to an instance of a resource
	Ref string `json:"ref"`
}

// FlexeraIamPrincipalKind The resource's type
type FlexeraIamPrincipalKind string

// BudgetReportParams defines parameters for BudgetReport.
type BudgetReportParams struct {
	// Filter The filter query string parameter allows to filter reports.
	//
	// ***Note:*** The value for the filter query parameter must be a URL-encoded query string.
	// | Filter | Required | Description | Allowed Operator | Behavior | Example |
	// | --- | --- | --- | --- | --- | --- |
	// | budgeted | No | Filter to limit returned data to just budgeted or unbudgeted rows. If `true`, only the budgeted rows will be returned. If `false`, only the unbudgeted rows will be returned.| eq | Equal - For a match, the budgeted dimension must be equal to the supplied value. | budgeted eq true |
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`

	// StartAt Earliest timestamp (inclusive) of the returned budget and spend. Consists of a year and month in YYYY-MM format. Will be interpreted as UTC, which is used for period boundaries.
	StartAt string `form:"startAt" json:"startAt"`

	// EndAt Latest timestamp (exclusive) of the budget and spend. Consists of a year and month in YYYY-MM format. Will be interpreted as UTC, which is used for period boundaries. No records will be returned on or after this timestamp.
	EndAt string `form:"endAt" json:"endAt"`

	// Summarized Aggregates the rows for multiple year-months into a single row. Default `false`.
	Summarized *bool `form:"summarized,omitempty" json:"summarized,omitempty"`

	// Dimensions The list of supported dimensions by which to report budget spend.
	Dimensions *[]string `form:"dimensions,omitempty" json:"dimensions,omitempty"`
}

// BudgetCreateJSONRequestBody defines body for BudgetCreate for application/json ContentType.
type BudgetCreateJSONRequestBody = CreateRequestBody

// BudgetUpdateJSONRequestBody defines body for BudgetUpdate for application/json ContentType.
type BudgetUpdateJSONRequestBody = CreateRequestBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// BudgetIndex request
	BudgetIndex(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BudgetCreateWithBody request with any body
	BudgetCreateWithBody(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BudgetCreate(ctx context.Context, orgId int, body BudgetCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BudgetDelete request
	BudgetDelete(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BudgetShow request
	BudgetShow(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BudgetUpdateWithBody request with any body
	BudgetUpdateWithBody(ctx context.Context, orgId int, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BudgetUpdate(ctx context.Context, orgId int, id string, body BudgetUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BudgetReport request
	BudgetReport(ctx context.Context, orgId int, id string, params *BudgetReportParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CloudVendorAccountIndex request
	CloudVendorAccountIndex(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) BudgetIndex(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBudgetIndexRequest(c.Server, orgId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BudgetCreateWithBody(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBudgetCreateRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BudgetCreate(ctx context.Context, orgId int, body BudgetCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBudgetCreateRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BudgetDelete(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBudgetDeleteRequest(c.Server, orgId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BudgetShow(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBudgetShowRequest(c.Server, orgId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BudgetUpdateWithBody(ctx context.Context, orgId int, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBudgetUpdateRequestWithBody(c.Server, orgId, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BudgetUpdate(ctx context.Context, orgId int, id string, body BudgetUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBudgetUpdateRequest(c.Server, orgId, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BudgetReport(ctx context.Context, orgId int, id string, params *BudgetReportParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBudgetReportRequest(c.Server, orgId, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CloudVendorAccountIndex(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCloudVendorAccountIndexRequest(c.Server, orgId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewBudgetIndexRequest generates requests for BudgetIndex
func NewBudgetIndexRequest(server string, orgId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-analytics/v1/orgs/%s/budgets", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBudgetCreateRequest calls the generic BudgetCreate builder with application/json body
func NewBudgetCreateRequest(server string, orgId int, body BudgetCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBudgetCreateRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewBudgetCreateRequestWithBody generates requests for BudgetCreate with any type of body
func NewBudgetCreateRequestWithBody(server string, orgId int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-analytics/v1/orgs/%s/budgets", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewBudgetDeleteRequest generates requests for BudgetDelete
func NewBudgetDeleteRequest(server string, orgId int, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-analytics/v1/orgs/%s/budgets/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBudgetShowRequest generates requests for BudgetShow
func NewBudgetShowRequest(server string, orgId int, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-analytics/v1/orgs/%s/budgets/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBudgetUpdateRequest calls the generic BudgetUpdate builder with application/json body
func NewBudgetUpdateRequest(server string, orgId int, id string, body BudgetUpdateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBudgetUpdateRequestWithBody(server, orgId, id, "application/json", bodyReader)
}

// NewBudgetUpdateRequestWithBody generates requests for BudgetUpdate with any type of body
func NewBudgetUpdateRequestWithBody(server string, orgId int, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-analytics/v1/orgs/%s/budgets/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewBudgetReportRequest generates requests for BudgetReport
func NewBudgetReportRequest(server string, orgId int, id string, params *BudgetReportParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-analytics/v1/orgs/%s/budgets/%s/report", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Filter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "filter", runtime.ParamLocationQuery, *params.Filter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "startAt", runtime.ParamLocationQuery, params.StartAt); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "endAt", runtime.ParamLocationQuery, params.EndAt); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Summarized != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "summarized", runtime.ParamLocationQuery, *params.Summarized); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Dimensions != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "dimensions", runtime.ParamLocationQuery, *params.Dimensions); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCloudVendorAccountIndexRequest generates requests for CloudVendorAccountIndex
func NewCloudVendorAccountIndexRequest(server string, orgId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/finops-analytics/v1/orgs/%s/cloud-vendor-accounts", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// BudgetIndexWithResponse request
	BudgetIndexWithResponse(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*BudgetIndexResponse, error)

	// BudgetCreateWithBodyWithResponse request with any body
	BudgetCreateWithBodyWithResponse(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BudgetCreateResponse, error)

	BudgetCreateWithResponse(ctx context.Context, orgId int, body BudgetCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*BudgetCreateResponse, error)

	// BudgetDeleteWithResponse request
	BudgetDeleteWithResponse(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*BudgetDeleteResponse, error)

	// BudgetShowWithResponse request
	BudgetShowWithResponse(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*BudgetShowResponse, error)

	// BudgetUpdateWithBodyWithResponse request with any body
	BudgetUpdateWithBodyWithResponse(ctx context.Context, orgId int, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BudgetUpdateResponse, error)

	BudgetUpdateWithResponse(ctx context.Context, orgId int, id string, body BudgetUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*BudgetUpdateResponse, error)

	// BudgetReportWithResponse request
	BudgetReportWithResponse(ctx context.Context, orgId int, id string, params *BudgetReportParams, reqEditors ...RequestEditorFn) (*BudgetReportResponse, error)

	// CloudVendorAccountIndexWithResponse request
	CloudVendorAccountIndexWithResponse(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*CloudVendorAccountIndexResponse, error)
}

type BudgetIndexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BudgetList
}

// Status returns HTTPResponse.Status
func (r BudgetIndexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BudgetIndexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BudgetCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Budget
}

// Status returns HTTPResponse.Status
func (r BudgetCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BudgetCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BudgetDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r BudgetDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BudgetDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BudgetShowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Budget
}

// Status returns HTTPResponse.Status
func (r BudgetShowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BudgetShowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BudgetUpdateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r BudgetUpdateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BudgetUpdateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BudgetReportResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BudgetReportRowList
}

// Status returns HTTPResponse.Status
func (r BudgetReportResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BudgetReportResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CloudVendorAccountIndexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CloudVendorAccountsList
}

// Status returns HTTPResponse.Status
func (r CloudVendorAccountIndexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CloudVendorAccountIndexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// BudgetIndexWithResponse request returning *BudgetIndexResponse
func (c *ClientWithResponses) BudgetIndexWithResponse(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*BudgetIndexResponse, error) {
	rsp, err := c.BudgetIndex(ctx, orgId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBudgetIndexResponse(rsp)
}

// BudgetCreateWithBodyWithResponse request with arbitrary body returning *BudgetCreateResponse
func (c *ClientWithResponses) BudgetCreateWithBodyWithResponse(ctx context.Context, orgId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BudgetCreateResponse, error) {
	rsp, err := c.BudgetCreateWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBudgetCreateResponse(rsp)
}

func (c *ClientWithResponses) BudgetCreateWithResponse(ctx context.Context, orgId int, body BudgetCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*BudgetCreateResponse, error) {
	rsp, err := c.BudgetCreate(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBudgetCreateResponse(rsp)
}

// BudgetDeleteWithResponse request returning *BudgetDeleteResponse
func (c *ClientWithResponses) BudgetDeleteWithResponse(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*BudgetDeleteResponse, error) {
	rsp, err := c.BudgetDelete(ctx, orgId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBudgetDeleteResponse(rsp)
}

// BudgetShowWithResponse request returning *BudgetShowResponse
func (c *ClientWithResponses) BudgetShowWithResponse(ctx context.Context, orgId int, id string, reqEditors ...RequestEditorFn) (*BudgetShowResponse, error) {
	rsp, err := c.BudgetShow(ctx, orgId, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBudgetShowResponse(rsp)
}

// BudgetUpdateWithBodyWithResponse request with arbitrary body returning *BudgetUpdateResponse
func (c *ClientWithResponses) BudgetUpdateWithBodyWithResponse(ctx context.Context, orgId int, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BudgetUpdateResponse, error) {
	rsp, err := c.BudgetUpdateWithBody(ctx, orgId, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBudgetUpdateResponse(rsp)
}

func (c *ClientWithResponses) BudgetUpdateWithResponse(ctx context.Context, orgId int, id string, body BudgetUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*BudgetUpdateResponse, error) {
	rsp, err := c.BudgetUpdate(ctx, orgId, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBudgetUpdateResponse(rsp)
}

// BudgetReportWithResponse request returning *BudgetReportResponse
func (c *ClientWithResponses) BudgetReportWithResponse(ctx context.Context, orgId int, id string, params *BudgetReportParams, reqEditors ...RequestEditorFn) (*BudgetReportResponse, error) {
	rsp, err := c.BudgetReport(ctx, orgId, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBudgetReportResponse(rsp)
}

// CloudVendorAccountIndexWithResponse request returning *CloudVendorAccountIndexResponse
func (c *ClientWithResponses) CloudVendorAccountIndexWithResponse(ctx context.Context, orgId int, reqEditors ...RequestEditorFn) (*CloudVendorAccountIndexResponse, error) {
	rsp, err := c.CloudVendorAccountIndex(ctx, orgId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCloudVendorAccountIndexResponse(rsp)
}

// ParseBudgetIndexResponse parses an HTTP response from a BudgetIndexWithResponse call
func ParseBudgetIndexResponse(rsp *http.Response) (*BudgetIndexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BudgetIndexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BudgetList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBudgetCreateResponse parses an HTTP response from a BudgetCreateWithResponse call
func ParseBudgetCreateResponse(rsp *http.Response) (*BudgetCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BudgetCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Budget
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseBudgetDeleteResponse parses an HTTP response from a BudgetDeleteWithResponse call
func ParseBudgetDeleteResponse(rsp *http.Response) (*BudgetDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BudgetDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseBudgetShowResponse parses an HTTP response from a BudgetShowWithResponse call
func ParseBudgetShowResponse(rsp *http.Response) (*BudgetShowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BudgetShowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Budget
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBudgetUpdateResponse parses an HTTP response from a BudgetUpdateWithResponse call
func ParseBudgetUpdateResponse(rsp *http.Response) (*BudgetUpdateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BudgetUpdateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseBudgetReportResponse parses an HTTP response from a BudgetReportWithResponse call
func ParseBudgetReportResponse(rsp *http.Response) (*BudgetReportResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BudgetReportResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BudgetReportRowList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCloudVendorAccountIndexResponse parses an HTTP response from a CloudVendorAccountIndexWithResponse call
func ParseCloudVendorAccountIndexResponse(rsp *http.Response) (*CloudVendorAccountIndexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CloudVendorAccountIndexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CloudVendorAccountsList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
