package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

const servicesFileName = generatedPrefix + "services.go"

// serviceEntry mirrors one value of the unified spec's root
// x-flexera-services registry (see unified-openapi generator/README.md).
type serviceEntry struct {
	ID                string
	Title             string   `json:"title"`
	Name              string   `json:"name"`
	Vendor            string   `json:"vendor"`
	Version           string   `json:"version"`
	SpecID            string   `json:"specId"`
	OperationIDPrefix string   `json:"operationIdPrefix"`
	SourceURL         string   `json:"sourceUrl"`
	Tags              []string `json:"tags"`
}

type serviceMetadata struct {
	Services   []serviceEntry
	Operations map[string]string // operationId -> service id
}

// computeServiceMetadata extracts the service registry and the
// operationId->service mapping from the merged spec's x-flexera-service
// extensions. A spec with neither the registry nor any operation-level
// annotation yields empty metadata (older snapshots); a partially annotated
// spec is an error so the generated lookup can never silently miss operations.
func computeServiceMetadata(specData []byte) (serviceMetadata, error) {
	var doc struct {
		Services map[string]serviceEntry               `json:"x-flexera-services"`
		Paths    map[string]map[string]json.RawMessage `json:"paths"`
	}
	if err := json.Unmarshal(specData, &doc); err != nil {
		return serviceMetadata{}, fmt.Errorf("parse spec: %w", err)
	}

	result := serviceMetadata{Operations: map[string]string{}}
	var missing []string
	for path, item := range doc.Paths {
		for method, raw := range item {
			switch method {
			case "get", "put", "post", "delete", "options", "head", "patch", "trace":
			default:
				continue
			}
			var op struct {
				OperationID string `json:"operationId"`
				Service     string `json:"x-flexera-service"`
			}
			if err := json.Unmarshal(raw, &op); err != nil {
				return serviceMetadata{}, fmt.Errorf("parse %s %s: %w", strings.ToUpper(method), path, err)
			}
			if op.OperationID == "" {
				continue
			}
			if op.Service == "" {
				missing = append(missing, op.OperationID)
				continue
			}
			if _, ok := doc.Services[op.Service]; !ok {
				return serviceMetadata{}, fmt.Errorf("operation %s references unregistered service %q", op.OperationID, op.Service)
			}
			result.Operations[op.OperationID] = op.Service
		}
	}
	if len(result.Operations) == 0 && len(doc.Services) == 0 {
		return result, nil
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		return serviceMetadata{}, fmt.Errorf("operations missing x-flexera-service: %s", strings.Join(missing, ", "))
	}

	for id, entry := range doc.Services {
		entry.ID = id
		result.Services = append(result.Services, entry)
	}
	sort.Slice(result.Services, func(i, j int) bool { return result.Services[i].ID < result.Services[j].ID })
	return result, nil
}

func serviceConstName(id string) string {
	return "Service" + componentNamespace(id)
}

// renderServicesFile renders the Service constants, registry, and
// operationId lookup table consumed by services.go.
func renderServicesFile(packageName, generator string, meta serviceMetadata) ([]byte, []string, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by cmd/split-client from unified-openapi/openapi3.json using %s. DO NOT EDIT.\n", generator)
	fmt.Fprintf(&buf, "// Regenerate via `make generate` (see generate_client.sh).\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", packageName)

	declarations := []string{"serviceRegistry", "operationServices"}
	if len(meta.Services) > 0 {
		buf.WriteString("// Service identifiers from the unified spec's x-flexera-services registry.\n")
		buf.WriteString("const (\n")
		for _, svc := range meta.Services {
			name := serviceConstName(svc.ID)
			fmt.Fprintf(&buf, "\t// %s is the %s service.\n", name, svc.Title)
			fmt.Fprintf(&buf, "\t%s Service = %q\n", name, svc.ID)
			declarations = append(declarations, name)
		}
		buf.WriteString(")\n\n")
	}

	buf.WriteString("// serviceRegistry lists every service, sorted by ID.\n")
	buf.WriteString("var serviceRegistry = []ServiceInfo{\n")
	for _, svc := range meta.Services {
		fmt.Fprintf(&buf, "\t{ID: %s, Title: %q, Name: %q, Vendor: %q, Version: %q, SpecID: %q, OperationIDPrefix: %q, SourceURL: %q, Tags: []string{",
			serviceConstName(svc.ID), svc.Title, svc.Name, svc.Vendor, svc.Version, svc.SpecID, svc.OperationIDPrefix, svc.SourceURL)
		for i, tag := range svc.Tags {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(&buf, "%q", tag)
		}
		buf.WriteString("}},\n")
	}
	buf.WriteString("}\n\n")

	ids := make([]string, 0, len(meta.Operations))
	for id := range meta.Operations {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	buf.WriteString("// operationServices maps every operationId to its owning service.\n")
	buf.WriteString("var operationServices = map[string]Service{\n")
	for _, id := range ids {
		fmt.Fprintf(&buf, "\t%q: %s,\n", id, serviceConstName(meta.Operations[id]))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, nil, fmt.Errorf("gofmt generated services file: %w", err)
	}
	sort.Strings(declarations)
	return formatted, declarations, nil
}
